### ISSUE TITLE
`WorkflowHistoryView` should allow other users to complete workflow, and should not return 403 status for Integrity Errors

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#10153]
https://github.com/archesproject/arches/blob/dev/7.5.x/arches/app/views/workflow_history.py#L51

It is possible to have receive an `IntegrityError` without having a 'wrong user' save a workflow. Furthermore one would expect that a user that didn't start the workflow should be able to complete the workflow.

**Comment by jacobtylerwalls** [comment]
Hey, just wanted to jot down the context I had around this before I forget 🧠:

- Limiting the user to retrieving their own workflows was a baby step discussed [here](https://github.com/archesproject/arches/issues/9923#issuecomment-1738197312). But yeah, I'd expect in the next tranche of work we'd want to define who/what roles can access whose workflows. AfS seems on the [cusp](https://github.com/archesproject/arches-for-science/pull/1366) of implementing object-level permissions for plugins, so that would probably need to be checked also.
- I do see that we're not inspecting the IntegrityError to ensure it's truly a permission conflict, but just wanted to mention that this except is what's supporting this test case:
https://github.com/archesproject/arches/blob/d084723fd602d81cc88f357162878fc27e5a069c/tests/views/workflow_tests.py#L82-L86
(This section of the view is just a ripoff of the source for `update_or_create()`. Ryan was originally using `update_or_create()`, which I like, but when I wanted to support POSTing incomplete representations of the workflow data I found we'll need to wait to use `update_or_create()` until Django 5 which will allow providing distinct defaults for update vs. create.)

**Comment by chiatt** [comment]
Allow superuser to view and open all incomplete workflows. Add username to incomplete workflow modal for admin user
