### ISSUE TITLE
Remove hard coded geometry point limit

### ISSUE THREAD

**Issue by bferguso** [archesproject/arches#10656]
In uploading a KML file with a fairly large number of points we encountered a hard coded 1500 point limit in the datatype validation. In my dev instance I increased that value to 6500 and was able to upload a geometry with approx 5800 points without issue.

The limit appears (I believe) to be about the max ES field data size. Wondering if this hard coded point count limit should be changed to the actual size of the encoded geometry for ES.

If a point limit needs to be maintained in the code, perhaps that should be moved into the settings rather than be hard coded in the datatype?

**Comment by whatisgalen** [comment]
> If a point limit needs to be maintained in the code, perhaps that should be moved into the settings rather than be hard coded in the datatype?

+10000 to this -- I think it makes sense to put any kind of hard-coded limit in settings that isn't a non-negotiable

**Comment by chiatt** [comment]
I think you're right @bferguso. The 1500 limit was just a rough estimate as to the number of vertices that would result in a string exceeding the ES limit. The problem has as much to do with the precision of your geometries as it does the number of them, so if your precision isn't particularly high, you could potentially load more vertices were it not for that cap of 1500.

[More details on the history of this issue](https://github.com/archesproject/arches/issues/340)

If possible, we should try to find a way to detect whether a geometry exceeds the ES limit (as you suggest @bferguso) and avoid a new setting because the people that will encounter this error while performing a bulk load or uploading a KML file generally aren't going to be able to modify it.

**Comment by bferguso** [comment]
Closing - This was addressed by @ryan86 in this issue: https://github.com/archesproject/arches/issues/10855, PR here: https://github.com/archesproject/arches/pull/10922.
