### ISSUE TITLE
`apps.py` is generated with a mixed-case classname

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#11195]
for multi-word projects (eg ca_shpo_online), creating an `apps.py` results in the classname having mixed casing (eg `Ca_Shpo_OnlineConfig`)

Similarly `verbose_name` has mixed casing (eg `verbose_name = "Ca_Shpo_Online"`). The assumption here is `verbose_name = "Ca Shpo Online"`. Building on that, I'm not sure I'm seeing where `verbose_name` is referenced. Is it necessary?

**Comment by jacobtylerwalls** [comment]
> Building on that, I'm not sure I'm seeing where verbose_name is referenced. Is it necessary?

It defaults to `label.title()` if you don't give an explicit one. It appears in the Django admin, maybe elsewhere. I was hoping to "leave it in the user's face" to encourage them to pick a better one, but maybe it's best to delete and only let the users that care about it define one. I've already left a comment on the Arches for Science PR, so that one's taken care of.

**Comment by chrabyrd** [comment]
> > Building on that, I'm not sure I'm seeing where verbose_name is referenced. Is it necessary?
> 
> It defaults to `label.title()` if you don't give an explicit one. It appears in the Django admin, maybe elsewhere. I was hoping to "leave it in the user's face" to encourage them to pick a better one, but maybe it's best to delete and only let the users that care about it define one. I've already left a comment on the Arches for Science PR, so that one's taken care of.

Ah this is fair. I honestly don't have a strong opinion about if it exists or not, just wondered why it was there and what the casing/delineation should be. So def up to your judgement about it 👍
