### ISSUE TITLE
Bulk Data Manager - Data Deletion function cannot be rolled back, needs more explicit language to alert users

### ISSUE THREAD

**Issue by alyssavloera** [archesproject/arches#11405]
Once a bulk deletion task is submitted it cannot be rolled back like the other tasks in the Bulk Data Manager. This is not apparent to the user until after the task is started and completed.

It seems as though the user should be alerted to the inability to rollback the task before hitting the start button.
Is there a manual way to roll back the deletion, perhaps via Celery task management? Or is this a full deletion method? The objects deleted were in this example were tiles. 

![image](https://github.com/user-attachments/assets/10e0b5de-b8e1-496a-8c22-4ef223be9f1d)

**Comment by chiatt** [comment]
Thanks for submitting this issue @alyssavloera. Unfortunately there isn't a way to roll back tile deletion in Arches 7. Although it is a feature that we could support in a future version because the tile data still exists in the edit log. I think your suggestion of at least warning users is a good idea.
