### ISSUE TITLE
Arches error blocks `manage.py` if using dev/branch and not `DEBUG`

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#11487]
If you install Arches on a dev branch like `dev/7.6.x` and try to run Arches with `DEBUG = False` it issues an error and prevents you from running any `manage.py` commands because the `__version__` might look like this: "7.6.0-a10" which fails on `arches>=7.6.0,<7.7.0`. Instead, it should say something about how you're not running a stable version and issue a warning instead of an error. Relevant code [here](https://github.com/archesproject/arches/blob/dev/7.6.x/arches/apps.py#L142).

**Comment by jacobtylerwalls** [comment]
Hey @whatisgalen. I think this is failing because 7.6.0-a10 < 7.6.0 final, so it's failing your version requirement. Would recommend either loosening your version requirement to include dev versions, or if you prefer not to for some reason silencing the system check with SILENCED_SYSTEM_CHECKS.

The situation should be roughly the same as with the old MIN_ARCHES_VERSION check. Let me know if that helps.
