### ISSUE TITLE
Can't search for numbers in the search bar

### ISSUE THREAD

**Issue by CWDamm-Kint** [archesproject/arches#11619]
When searching for a number, the search bar appears to treat it as a string. When you try to click on the search bar to cancel this behaviour, you run into a related issue, where search text disappears upon clicking the search bar: https://github.com/archesproject/arches/issues/11618 

https://github.com/user-attachments/assets/3cd189ec-7468-4895-a577-53fa3c5f1671

**Comment by CWDamm-Kint** [comment]
Tested in 7.6 and 8.0.x

**Comment by chiatt** [comment]
I think the issue here is that the search bar performs a 'term' search, so it only searches for string terms. I think other datatypes such as dates and edtf won't work here either. I can see how people might expect numbers to be treated as terms, though. We could probably index them that way. @apeters might have more insight on this.

**Comment by chiatt** [comment]
It looks like all we would have to do is add a `get_search_terms` method to the number datatype.

**Comment by apeters** [comment]
It would be easy enough as @chiatt mentioned all you need to do is add that method to the datatype.
