### ISSUE TITLE
`SEARCH_EXPORT_LIMIT` in `settings.py` ignored by whatever in Arches frontend system settings

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#11697]
Whatever value you set in your project `settings.py` file e.g. `SEARCH_EXPORT_LIMIT = 500000` gets ignored by the value in the tile nested under Arches System Settings:

<img width="1188" alt="Screenshot 2024-12-18 at 4 00 06 PM" src="https://github.com/user-attachments/assets/6589896e-55e4-4018-b967-2f3f98345f9a" />

**Comment by jacobtylerwalls** [comment]
Hey @whatisgalen, I asked a related question during a recent standup. (I can't remember if you were on the call that day.)

I heard that, contrary to the docstring in the `SystemSettings` class, the system setting tiles are _always_ supposed to override the settings.py settings. It's a bug that this only happens correctly when running under wsgi.py instead the devserver as described in #11660.

There were also some murmurs about decoupling the Django settings from the configurable settings / system settings graph in a future version.

Given that, isn't this expected behavior?

**Comment by jacobtylerwalls** [comment]
The inheritance order is clarified [here](https://arches.readthedocs.io/en/stable/configuring/settings-beyond-the-ui/#settings-inheritance)
