### ISSUE TITLE
Create Content for In-app Resource Editor Help Panel

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#1182]
Content needs to be created for the help panels that will be accessible to users while they are entering data through the data entry forms, as per #1180.

The content should contain links to tutorials, step-guides, and general information about these menus.

**Comment by mradamcox** [comment]
@dwuthrich could you take a look and let me know what you think? Two places to look, intro content in the resource editor "landing page" (where you can choose a resource model to create a new resource with) and full content in the resource editor page while editing a resource.

The gif for step 3 of the resource relations is a little strange because of the current strange behavior of the related resource grid layout.

**Comment by dwuthrich** [comment]
@mradamcox Both the "landing page" and the resource editor content look great!  

FYI, on the issue for step 3: looks like the problem is that you didn't click on the record in the table before starting to  edit the relationship (you can tell this because the modal form does not list the related resource).  

This is a pretty blatant UX problem (not the fault of the user).  We should make it clearer that a user needs to select the resource whose relation is being edited before allowing a user to edit the relationship.  I'll start working on a UX fix.

**Comment by mradamcox** [comment]
Ok, I see what you mean. There is still some strangeness with the form but I will remake that gif and make sure to select the relation before editing it and saving it.

**Comment by mradamcox** [comment]
@dwuthrich as for a fix, disregarding the strange form behavior, one improvement would just be to disable the "relation properties" button until a relation has been selected in the grid. I'll write that step into the docs anyway.

**Comment by dwuthrich** [comment]
@mradamcox Yup, I was thinking the same thing
