### ISSUE TITLE
Function: Upload File Function causes internal error

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1191]
### Bug Report

see: http://recordit.co/YSdTmKe5lX

**Comment by apeters** [comment]
There only seems to be an issue when managing files where the card group that file upload is a part of has more then one card.  Additionally, I've only seen an issue when deleting uploaded files.

**Comment by robgaston** [comment]
There is some additional regression around the file upload widget since moving over to using the function on the backend - tile records are no longer being properly updated w/ the url to the file and therefore links and images are broken in the form and report after saving a tile.  I will try to get to the bottom of both of these issues as part of this ticket.

**Comment by apeters** [comment]
I think that what Rob was that he didn't add a function to manage file upload.
The error that Dennis saw seems to be fixed in the latest.

**Comment by dwuthrich** [comment]
Error appears to be resolved
