### ISSUE TITLE
Develop strategy to index tile data to support search

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#1323]
Keep in mind that we may need to create a way to automatically map datatypes to ES datatypes.
Need to support fuzzy search.

**Comment by mradamcox** [comment]
In v3, the map_layers index was used to supply the resource data used for display on the map, but it was pretty bar bones. If a similar index is developed for v4, it would be good to include a qualifier node that is attached to the geometry. I know this depends on the graph itself, but in v3 I had to use the resource index (which included the entire graph) in order to sift through geometries if I wanted to display geometries based on a certain type.

Given the variability in use cases, this may not be worth implementing, but I just wanted to point it out.

**Comment by apeters** [comment]
dependent on #1541
