### ISSUE TITLE
Create widget to generate a time based filter for search using a sunburst chart

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#1327]
see http://archesproject.github.io/mockups/arches_resource_editor_v3.html for the mockup

this filter will coordinate with the dropdown based time filter widget (#1326)

The widget will provide for the following functionality:
 - The sunburst chart will be zoomable (https://bl.ocks.org/kerryrodden/477c1bfb081b783f80ad)
 - Metadata about items in the chart will be displayed on hover (ie, to/from dates, etc...)
 
The widget will also require a configuration that identifies the date ranges of each bucket in the chart.
Dennis was using a simple comma separated file for this in the mockup. 

see [js/views/search/time-filter.js](https://github.com/archesproject/arches/blob/master/arches/app/media/js/views/search/time-filter.js) for an example of what was done in Arches v3

![screen shot 2016-12-06 at 12 16 25 pm](https://cloud.githubusercontent.com/assets/823773/20942005/28732d30-bbae-11e6-88ed-218d2aa0bd74.png)

**Comment by robgaston** [comment]
This ticket will focus on simply creating the binding that will create this D3 viz using mock data.

**Comment by robgaston** [comment]
I've been having some difficulty implementing the zoom in/out feature.  Currently, you can zoom in, but not all the way back out.

I found [this example](http://tiven.wang/apps/d3/zoom-sequence-sunburst.html) which conflates the ["sequences sunburst"](https://bl.ocks.org/kerryrodden/7090426) and ["zoomable sunburst"](http://bl.ocks.org/mbostock/4348373) examples to achieve what (I think) we want, but it is unfortunately written against an old version of the API and I've not yet had success integrating this code and updating for the version of D3 that we're using.

I am considering opening up another ticket for this bug so that we can close this larger one out.

**Comment by robgaston** [comment]
I opened a ticket for the above mentioned known issue w/ zooming: https://github.com/archesproject/arches/issues/1506

**Comment by dwuthrich** [comment]
meets requirements
