### ISSUE TITLE
Create view and associated widgets to manage advanced search filters

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#1328]
see http://archesproject.github.io/mockups/arches_resource_editor_v3.html for the mockup
Load the page, press the related resources button, then the saved search or advanced search button.

@dwuthrich There are a few questions I have about this component:
- Will we be able to persist adv. search filters in the URL (using GET verbs) or because there is no limit to the number of filters allowed to be added could this cause a problem for searches with many filters?  Maybe we shouldn't worry about this at the moment.
- Should nodes within a node group be searched as a unit? (for example if a User Name is managed as a First and Last Name, should a search for First Name "John" and Last Name "Smith" return resources with any First and Last Name combination that satisfies the search or only resources that have a nodegroup with a First and Last Name that matches the search)
- Do nodes in the left panel need to be grouped by resource type?  
- What nodes do we show in the left panel?  I'm assuming not any spatial geometry nodes, but what about any others?

![screen shot 2016-12-06 at 11 39 04 am](https://cloud.githubusercontent.com/assets/823773/20942321/c9747814-bbaf-11e6-9c80-51c0082c47f6.png)

**Comment by mradamcox** [comment]
I don't know if this would be helpful (because I haven't examined it further), but in his v3 implementation, Bojan Kastelic implemented something similar. You can see it in action [here](http://zbiva.zrc-sazu.si/search_objects) (click "show advanced search") and here's the repo: https://github.com/bojankastelic/zbiva.

**Comment by dwuthrich** [comment]
@apeters:

- Will we be able to persist adv. search filters in the URL (using GET verbs) or because there is no limit to the number of filters allowed to be added could this cause a problem for searches with many filters? Maybe we shouldn't worry about this at the moment.

Not sure what you are asking here.

- Should nodes within a node group be searched as a unit? (for example if a User Name is managed as a First and Last Name, should a search for First Name "John" and Last Name "Smith" return resources with any First and Last Name combination that satisfies the search or only resources that have a nodegroup with a First and Last Name that matches the search)

Yes, I think users would expect node groups to be searched as a unit

- Do nodes in the left panel need to be grouped by resource type?
That would be a nice refinement.  That way users would know that they are building a search on a particular node group within a model (as opposed to all node groups called "name")

- What nodes do we show in the left panel? I'm assuming not any spatial geometry nodes, but what about any others?
No need for geometry nodes or date nodes.  Not sure what should happen with file data types.  Perhaps the advanced search is smart enough to expose the "searchable content" of more sophisticated data types such as cyrus' charting data type and Rob's IIIF data type.

**Comment by dwuthrich** [comment]
meets requirments
