### ISSUE TITLE
UX for defining whether subcards will exist in a branch

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#1480]
Dennis and I had a conversation in which it became apparent that there is a simple binary decision to be made when creating a branch.  The decision is: will this branch have its data collecting nodes in subcards, or in the primary card?

The current UI does not support a good UX to make this decision in a transparent way.

**Comment by robgaston** [comment]
A potential solution to this problem would be to use a three state radio button instead of our current binary "Make Card" switch.

The three states would be something like (names probably need improvement):
- Member (default)
- Card Container
- Card

Point being, a user would have to explicitly declare a card as a 'Card Container', embracing all that is implied by that.

Nodes inside of 'Card Containers' could not themselves be set as 'Card Containers', and only nodes inside of 'Cards' could collect data.

These constraints are already applied, but since the transition from a 'Card' to a 'Card Container' is implied by the state of downstream nodes, it is unclear to then end user when this has occurred and why constraints might suddenly be applied seemingly mysteriously.

Forcing explicit declaration of 'Card Containers' would mitigate that mysterious behavior, as constraints would be applied/lifted based on an explicit user action (as opposed to implicitly based on graph state).

**Comment by mradamcox** [comment]
It seems like this could be very regimented, taking much of the burden of choice off of the user.

The top node must be either be a Card or a Card Container (or, in the case of a single node used to construct a graph, neither). Everything after that should be automated:
root node: choose Card or Card Container or neither
second-level nodes: if root node is Card Container, these must all be Cards (no choice), if root node is Card, these must all be Members (no choice).
third-level+ nodes: these will always be Members (no choice).

(Perhaps this heirarchy doesn't fit the possibilities/constraints that come with using the CRM ontology, but I really think simplifying this for the users will go a long way.)

Thus, it seems like Member could even be removed as a choice, because that classification is always defined by what is upstream, and the user never needs to explicitly set it.

As Rob alludes, there would be a little mystery in how the Card / Card Container choice affects descendant nodes. I think I'd approach it by setting the root node as a Card by default. User then has an option to change to Card Container, or "None" to allow for the creation partial branches (like the single node branch that already exists). This is the only place that a user makes a change like this throughout the graph, and upon making it, all downstream nodes are automatically altered according to the rules described above. If errors would be caused by the change, a warning message would pop up describing the issue.

**Comment by azaroth42** [comment]
I think this is the right issue, if not please kick me out to a new one :)

We ran into this problem in several guises recently:

* Somehow a node that should have been a String was set to Semantic (its type was rdfs:Literal) and hence the textbox didn't appear. That let another part of the branch of that node be a sub-card. And then we couldn't set the Literal to be a string, as it would have violated the constraint.
* Conversely, on nodes where we wanted to have sub-cards but also had a string label, we couldn't make them sub-cards.

It is very typical to have a human readable label associated with every node in LOD, such that there's at least /something/ other than the URI to display to the user.  We follow this best practice, meaning that we can't use the sub-card capabilities at all.  It would be greatly appreciated if this restriction could be discussed as to alternative solutions.

For example, a "core" sub-card could be automatically created to hold all of the data collection nodes, and then all of the others would have their own sub-card.   Or, the UI could prompt for the name of a sub-card to put the data collection node in, allowing more customization if there are a ton of data collectors that should be split up.

**Comment by dwuthrich** [comment]
Rob,

The UX for card design is definitely an issue that we should discuss.  You’ve highlighted some examples where the UI should be more helpful or less confusing about how a particular node is configured.  

I’m beginning to wonder if the graph manager and card manager cards really ought to be more closely integrated.  Graph design drives card configuration (at least for now), and knowing how graph patterns influence card layout is not intuitive to say the least.  

We’ve put some constraints on graph shape to enable Arches to dynamically render data entry forms.  If these constraints are too limiting, then we should at least  discuss options that would allow a developer to extend graphs/cards in a way that doesn’t break Arches ability to dynamically build cards.

-Dennis

**Comment by azaroth42** [comment]
How about I come up to the city in January and we can talk through the design considerations? That seems too hard to do in an issue :)

**Comment by dwuthrich** [comment]
Yeah, a meeting in January sounds great.  Just let me know a couple of dates that would be convenient for you and I can make sure that either Rob or Alexei can also attend

**Comment by azaroth42** [comment]
Notes from said meeting:

The order of operations of adding different node types into the branch is important.  Adding a semantic node and then a data capture node (like a string label) has a different effect than the other way around.  The work around for the basic scenario of this issue is to first add all of the data capture nodes and make them sub-cards, and only then add the semantic nodes (again as sub-cards).  This won't solve all of the issues, but does move the chains at least a little further down the field.

**Comment by adamlodge** [comment]
I think this old an irrelevant given the latest graph editing capabilities.  Closing for now.
