### ISSUE TITLE
Navbar: Navbar for Resource Editor landing page displays two titles

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1571]
### Bug Report

To reproduce bug:

1. Go to "add resource" home page and notice grid of resource models.  The top-most nav bar shows the following text: "Resource Editor" and a "?" icon.  Underneath the top-most nav bar is a secondary nav bar that says "Resource Manager"

Expected behavior:

Should be consistent with "Arches Designer" landing page.  Either include secondary nav bar for each, or eliminate for both.  Preference would be to eliminate the secondary nav bar (and replace top-most nav bar in resource editor with the title/icon in the secondary nav bar)

**Comment by mradamcox** [comment]
I'm glad you logged this, because it's an outstanding question: 1. Leave the duplicate that has the subtitle 2. remove the duplicate and add a subtitle to the top bar 3. remove the duplicate and subtitle from all pages.

In my mind, these changes apply across all pages that inherit from base-manager, not just the resource editor and arches designer.
