### ISSUE TITLE
Map Widget:  Add tool to allow user to select a geometry from a layer/overlay/basemap for use in search or data creation

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1757]
### Bug Report

Use cases:

As an Arches user, I would like to find all resources within a set distance of an existing resource or an existing geometry (e.g.: a street or parcel) that exists in either an overlay or basemap

As an Arches editor, I would like to select an existing geometry from a basemap or overlay and copy it to use as the geometry for the instance I'm editing

**Comment by robgaston** [comment]
Features on map are made selectable by adding a property to the feature called `geojson` that contains the full geometry as geojson.  Any vectors with this property (regardless of source [arches or otherwise]) will be selectable when drawing resource features.

This feature can be tested with the sample 'rivers' layer provided in the repo.  To add this layer, run the `arches/tileserver/rivers.sql` file against your database and then run (from the project root w/ your virtualenv activated):
```python manage.py packages -o add_tileserver_layer -t arches/tileserver/rivers.json -n rivers```

**Comment by dwuthrich** [comment]
meets requirements
