### ISSUE TITLE
Saving geometry fails for Resource Model with "clean cache on edit" set to true

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1780]
### Bug Report

To reproduce:

1. select resource model in Map Layer Manager
2. Select caching tab
3. Toggle  "clean cache on edit" to true
4. Create an instance of the model, add a geometry, and save.
5. Attempt to edit the geometry and save the geometry of the instance and observe that the transaction fails

**Comment by robgaston** [comment]
@dwuthrich I just tested this on my machine and was unable to reproduce.

It is possible that either, some other step not listed above caused this issue, or that this issue is specific to your dataset in some way.

We know that large geometries can cause performance issues that may result in tile save crashing with this setting on - this is mentioned in the caching UI warning message:

> Cleaning the tile cache on edit is good for systems that require quick updates to map layers and are managing relatively small geometries (saving large geometries with automatic cache cleaning on will impact performance, sometimes severely). 

In any event, we will need more information to track this bug down

**Comment by robgaston** [comment]
As a note, automatic cache clearing **will not** work with all implementations.  For certain implementations (based on data volume, size of geometries) if caching is required, administrators will need to manage their own tile caches

**Comment by dwuthrich** [comment]
meets requirements
