### ISSUE TITLE
Add the ability to specify the default language that shows up in the language dropdown in the many RDM modals

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#1923]
It would be nice to specify the selected language that shows up in the list of available languages in the many dropdowns of the RDM.  Also, the languages should be sorted alphabetically.

Currently it looks like the last item in the list is selected by default.

**Comment by Philbox** [comment]
Can you make it so that it's possible to specify the sort order (currently Greek is showing up first). This is annoying as I have to change the language every time I add a concept.

**Comment by apeters** [comment]
Using the django admin page, an admin can set the `Isdefault` property on the `d_languages` table to make it so the desired language shows up first in the list.
Sorting would be another matter.

**Comment by chiatt** [comment]
Currently `isdefault` is set to True for all languages in the `d_languages` table, so a user has to click through all of them to turn each off (other than the one they want to use as the default).  Perhaps we should update the `d_languages` table when we build the database, setting `isdefault` to true only for the language defined by `LANGUAGE_CODE` in settings.py? I'd guess in most cases they would be the same. 

Maybe it's also worth considering adding this setting to the system settings graph.

**Comment by apeters** [comment]
I agree with all of the above

**Comment by chiatt** [comment]
Rather than editing the table on setup I added a function that checks if more than one language has `isdefault` set to True or if no languages have `isdefault` saved as True. If either is the case, then the default language is whatever settings.LANGUAGE_CODE is.  If only one language has `isdefault` saved as True, then that language is used as the default.  I'll create another ticket for the addition of the default language to the settings graph.

**Comment by jmunowitch** [comment]
This works as described. A Django Admin can go and set one DLanguage object as `isdefault`. If there is more than one, or none set with `isdefault`, settings.LANGUAGE_CODE is used.
