### ISSUE TITLE
Update Contribution Guide to latest practices

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches#1926]
In preparation of V4, we should update our Contribution Guide.

Here are a few things We should update:
- [x] Point people that if they want to work on the code, they need to install with the Developer Install instructions 
- [x] Point people on other ways to contribute, including updating documentation, creating example videos/workflows to do tasks, etc.
- [x] Point people to Follow Arches on [Twitter](https://twitter.com/archesproject), [Facebook](https://www.facebook.com/archesproject), [LinkedIn](https://www.linkedin.com/groups/4495003/profile), and [Starring the project on Github](https://ghbtns.com)
- [x] Integrate in naming conventions of Branches and add the Branching workflow
- [x] Instruct people to create their own working branches in their own Repo, not in the Arches Repo, and open a Pull Request from there. 
- [x] State that commits should be tagged with the ticket number associated with the commit - e.g. 'working on ticket number re #2309'
- [ ] Document the Zenhub Pipelines in use and how issues/tickets flow through those piplines
- [x] Document the CLA signing procedure

**Comment by mradamcox** [comment]
Ok, I've added everything in the checkboxes to the contributing guidelines on the wiki homepage. Only thing left on the checklist is ZenHub explanation, which I think would be better for @apeters to address.

However, there are currently PRs submitted that can't go through because they do not have a CLA attached. I think the details of the CLA must be documented in this same location, but it sounds like no one actually knows the details of the CLA right now. I'm unassigning myself.

**Comment by mradamcox** [comment]
Adding the CLA in a new checkbox, assigning @jmunowitch to write that up.

**Comment by jmunowitch** [comment]
Wiki has been updated to include CLA information.
