### ISSUE TITLE
Map Layer Manager: Zoom to resource extent

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#1961]
### Bug Report

When managing resources and overlays in the map layer manager, the map preview defaults to the whole world when selecting either a resource or overlay.  Instead, the map preview should zoom to the resource dataset extent (for resource layers) and the overlay extent when configuring overlays

**Comment by robgaston** [comment]
@dwuthrich we can use elasticsearch to determine the resource layers' spatial extents, but we don't  have any standard way to calculate the spatial extent of overlays, since the source for these layers is unknown (overlays can even include multiple sources).  We could have the user enter an extent manually on a per overlay basis in the settings form, if that is helpful.

**Comment by dwuthrich** [comment]
How about we just remember the map extent the user sets for the overlay (like we do for the map widget in the Card Manager).  That way, the user only has to navigate to the overlay extent once, and its easily updated just by map navigation/zoom.

**Comment by dwuthrich** [comment]
meets requirement
