### ISSUE TITLE
Resource-to-Resource Forced Directed Graph: Improve functionality of resource listing widget

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#2112]
### Bug Report

The force directed graph includes a widget that lists all nodes in the graph.  This widget should be enhanced to support:

1. When clicking on a entry in the list, this should highlight the corresponding node in the graph (this is the current behavior).  However, the node should remain selected UNTIL the user clicks on a node in the graph or on another entry in the listing widget (currently just hovering over a node removes the "selected" status).

**Comment by chiatt** [comment]
@dwuthrich  I've added both a selected and hovered state so that the selected state of a node will persist when hovering over nodes and list entries. I used a dashed stroke for the selected node (`.node-current-selected, .node-ancestor-selected`) to help it stand out in case a user selects a node color in the graph settings similar to the selection color. There is probably a better styling solution. If you want to make any refinements, here are the relevant classes:
```
.node-current-over, .node-ancestor-over {
    /* The currently moused-over node */
}

.node-current-selected, .node-ancestor-selected {
    /* The currently selected node */
}

.node-current-neighbor, .node-ancestor-neighbor {
    /* The neighboring nodes of the selected/moused-over node */
}

.library-card.relative.selected {
}

.library-card.relative.hovered {
}

.library-card.relative.selected.hovered {
}
```

**Comment by dwuthrich** [comment]
meets requirements
