### ISSUE TITLE
RDM: Adding Top Concepts

### ISSUE THREAD

**Issue by Philbox** [archesproject/arches#2199]
When creating a new thesaurus there is no possibility of adding the thesaurus underneath the Arches top level domain.
As such the new thesaurus itself sits alongside the Arches concept scheme. When you then add a concept to that thesaurus it treats it as a Top Concept so that when you search for it it only refers to itself For example in the thesaurus, Lincoln Monument Type, the concept Agriculture and subsistence is a top concept so when searching for it to add to a collection it appears as AGRICULTURE AND SUBSISTENCE (_AGRICULTURE AND SUBSISTENCE_)

#### Expected Behavior
When creating a new Thesaurus I should be add to add it into the Arches concept scheme so that it sits directly under Arches so that when I add a concept to it the thesaurus is included when searching, eg. AGRICULTURE AND SUBSISTENCE _(Lincoln Monument Type)_

#### Current Behavior
I cannot add a thesaurus to the Arches concept scheme

#### Context
Currently as I am adding a whole suite of vocabularies it is impossible to tell which vocabulary a concept belongs when adding it to a collection as the concept references itself. Consequently there is uncertainty as to whether the correct concept has been chosen.

**Comment by apeters** [comment]
I assume that when you say, "Add a new thesaurus" you mean "import a scheme":
![screen shot 2017-09-18 at 4 17 00 pm](https://user-images.githubusercontent.com/823773/30568944-e232e66a-9c8c-11e7-92b1-542c9aeb86ea.png)


If so, I can change the current functionality so that we can manage the parents of concept schemes like we do for concepts using the "Manage Parents" dropdown:
![screen shot 2017-09-18 at 4 21 13 pm](https://user-images.githubusercontent.com/823773/30569104-af900afc-9c8d-11e7-9f83-4fcaa7e20350.png)

But what this implies is that if you want to move the "Lincoln Monument Type" scheme under Arches (or better yet under a Scheme entitled "Lincoln") using the "Manage Parents" workflow, then that scheme ("Lincoln Monument Types") needs to be converted into an regular "Concept" because a skos:ConceptScheme can't be a range to another skos:ConceptScheme (see: https://www.w3.org/TR/2009/REC-skos-reference-20090818/#schemes)

Is that what you want to be able to do?

**Comment by Philbox** [comment]
Hi Alexei,
This may be less of an issue now I have a clean version of Arches to work with although the issue of labelling is still alive. Let me explain.

I have added 2 schemes HER Designation Type and MIDAS Area Type. Both contain a concept of 'Conservation Area'. When I add a corresponding Collection and search for the concepts to add to the dropdown I get the following.

![image](https://user-images.githubusercontent.com/16647003/30583962-42e547c6-9d20-11e7-90c9-addfb4725fd4.png)

As you can see there is no way to differentiate between the 2 concepts.

WHat I would like to see when adding a top concept is the scheme name. ie.

Conservation Area (_HER Designation Type_)
Conservation Area (_MIDAS Area Type_)

**Comment by ryan86** [comment]
meets requirements
