### ISSUE TITLE
Search Map Extent operation behaves improperly

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#2233]
### User Story
Gif will explain it well enough. The action is started with a single click. Looks like the search triggers a zoom which triggers a search, etc. Eventually it gets to full world extent and then errors.
![search map extent](https://user-images.githubusercontent.com/10427268/28125117-3df5dba6-66eb-11e7-8c52-c7761b5146bd.gif)
#### Acceptance Criteria
Recommend removing the button.

**Comment by chiatt** [comment]
@mradamcox The issue is probably not with the button, but rather the response of the map when search results are loaded. If the map extent is panned to the search results, a new extent search will be requested. This would call a new extent search and the pattern would continue recursively until your browser probably crashes. This wasn't the case previously. I'm not sure what changed.

**Comment by mradamcox** [comment]
Just a thought: instead of using some of the triggers that are causing this behavior, search by map extent could just make a polygon from the current view and then pass it to the normal buffer search (without a buffer). Then don't show the buffer on the map...

**Comment by chiatt** [comment]
That's basically how it works now except that the search updates on pan and zoom events.  @robgaston pointed out that Yelp updates the extent search only when a user presses the search button (that's at least the default) allowing users the opportunity to inspect their results without the search results updating. That's probably a better user experience. For now, I've merged in a fix, but I think we should discuss adopting the Yelp behavior with Dennis once he's back.

**Comment by mradamcox** [comment]
problem described in ticket is solved.
