### ISSUE TITLE
Full deletion of a geojson-feature-collection value

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#2298]
Currently you can't completely delete a geometry unless it is part of a card group. If the only node in a tile has a geojson-feature-collection datatype, all a user can do is clear all of the features from the geojson collection. They can't fully delete the value.  

This is a problem if a user has permissions to delete, but not update. In that scenario they can't remove any geometries and they can't delete the value either.

#### Expected Behavior
When all of the geometries are cleared from a map, the value for the map widget should be deleted.

**Comment by robgaston** [comment]
permission to delete but not update.... sounds a bit suspect.

My question would be: Permission to delete what?  An instance? a value? a tile?

I would assume, since permissions are at the node group level that this would be in reference to deleting an entire tile (rather than individual values.  Any mutation of a individual value inside a tile would qualify as an "update" in my mind rather than a "delete" (even if the value is being changed to `null`); ie it is an "update" of a tile regardless of what the underlying values are being set to.

Perhaps the problem is this: there is no way to delete a tile (once created) that has a cardinality of '1'....

**Comment by chiatt** [comment]
@robgaston I agree - it would be uncommon to have permissions to delete but not update, but it's possible.

Yeah - I guess specifically the issue is that you can't delete a tile that belongs to a card with a cardinality of n...1 or 1...1.

**Comment by robgaston** [comment]
That's right - I personally think "delete" permissions should refer to deleting a tile, and not a value.

I think the way to resolve this may be to allow for the deletion of tiles in the cases you've described, but the impacts of that would need to be fully considered.

**Comment by robgaston** [comment]
@apeters @dwuthrich can you two please weigh in on this?

**Comment by chiatt** [comment]
I should point out that this is fundamentally the same issue as #2299. I separated them into separate tickets so that the work could be divided into more discrete tasks.

**Comment by apeters** [comment]
"delete" permissions refer to nodegroups (and thus whole tiles).
It would seem to me that some of our widgets (maybe all?) would benefit from a "clear" button or something functionally similar.

**Comment by apeters** [comment]
this ticket has been superseded by https://github.com/archesproject/arches/issues/2740
