### ISSUE TITLE
Node-to-Node datatype

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#2402]
### User Story

As a data modeler, I need to refer to a node in an Arches branch from another branch in the same resource model.  This will allow me to represent "triangular" relationships in my resource model, an key capability to properly support more sophisticated datasets.

Exampled: The ability to model changing phases of an asset through time (e.g.: the asset was a "house" during period 1, a "castle" during period 2, and a monastery during period 3) in one branch.  Then referencing the asset as a "house" in a separate branch to describe its components (e.g.: asset type: house, component: chimney, material: brick).

Note that this construct allows us to describe multiple attributes of an asset without forcing the modeler to repeat nodes.  It is a way to "normalize" a resource model.

#### Acceptance Criteria
- [x] Arches allows me to select a node-to-node data type during model design and prompts me to select a node from a listing of nodes that already exist in the resource model
- [x] The graph manager allows me to define the property between the nodes
- [x] The node-to-node widget allows me to select a tile from the referenced node.  The widget will display the business data contained in the tile in a way that allows me to quickly review the content of the tile (the solution may use the report template associated with the tile and display it in some way as I make my selection)
- [x] Arches indexes my selection properly
- [ ] Arches supports data import/export of the data type 
- [ ] Unit Tests passed
- [ ] Documentation

#### Steps to Reproduce (for bugs)

1.
2.
3.
4.

#### Your Arches Information

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your Arches Install (optional):

**Comment by azaroth42** [comment]
Additional use cases from the Provenance work:

* The activity of selling an auction lot results in the Acquisition of the set of objects. Thus the E7 Auction activity P16_used_specific_object the Set, and P9 consists of the E8 Acquisition.  The E8 then transfers the title of the Set.

* The set consists of three objects. The Acquisition consists of three further Acquisitions that connect each object to the individual buyer(s) and/or seller(s).

We wouldn't want to have separate resource models for all of these, as we would end up with MANY little models that are mostly one-to-one with each other, just inter-connected.

**Comment by adamlodge** [comment]
Configurations for this datatype should only really be set when the node is in a resource model and not when it is a bonafide branch.  Configurations set for this datatype when in a branch are irrelevant because both the source and target nodeid values will be different when the branch gets imported into an actual resource model.  Beyond that, it is likely that more than half the time the target node will be in a different "branch" of the resource model. 

Reassigning to @robgaston to disable configs when a branch.

**Comment by dwuthrich** [comment]
@adamlodge @robgaston Disabling the datatype within a single branch is too restrictive.  Its completely acceptable to use the node value data type in a single branch, for example to model relationships between nodes in different "strands" (e.g.: cards) within a single branch.  

Adam, if this was your only issue with this ticket then please close.

**Comment by adamlodge** [comment]
@dwuthrich... I agree, but the target node (even if on a separate strand of the same branch) is not maintained on import to resource model.  This is due to the nodes within the branch being copied (and the nodes being assigned new UUID's) when appended to the resource model graph.  As such, the configuration is meaningless and has to be re-setup in the resource model anyway.

Per discussion with @robgaston, we think that it be more ideal for the node to maintain the config when imported to resource model, but that is a loftier goal, and likely brings up other issues we may prefer to address after this sprint.

There are other issues, but I plan to address them in other tickets as not to hold up closing of this ticket for the sprint.  But, per verbal discussion on this with @robgaston, he indicated that this fix would quick and simple to implement and solve the immediate problem.

**Comment by adamlodge** [comment]
Closing this ticket as the data type is functional. Will address enhancements in new ticket(s).
