### ISSUE TITLE
Images imported via a package aren't properly rendered in the header of an report

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#2545]
If you load the test-package-load package, you'll observe this behaviour with this report for the resource instance with this legacyid (00000000-0000-0000-0000-000lhdsnew09)

<img width="796" alt="screen shot 2017-10-11 at 1 56 21 pm" src="https://user-images.githubusercontent.com/823773/31466469-19ee50b0-ae8c-11e7-9652-4c71e285299f.png">

**Comment by adamlodge** [comment]
SF Planning observed that this issue occurs on import of image data - irrespective of use of package.  Bottom line is that it seems that images added to the system via import cannot be displayed as the header of a report.

**Comment by chiatt** [comment]
Possibly related to #2861

**Comment by chiatt** [comment]
I was not able to reproduce this issue in the latest

**Comment by adamlodge** [comment]
This doesnt seem to be working, but I'll check again after #3152 is resolved.

**Comment by chiatt** [comment]
The issue seems to be that you have to add a node in the report configuration. If you don't, then the report template does not know which node should drive the header. It would be easy to add a wee bit of logic to use any/all images in the resource instance if a user fails to specify a node.  Alternatively, we could highlight the importance of specifying a node in the report configuration.  


![screen shot 2018-03-22 at 3 25 24 pm](https://user-images.githubusercontent.com/1877663/37801849-65725c60-2de5-11e8-8ada-f736fecbef37.png)

**Comment by adamlodge** [comment]
it works
