### ISSUE TITLE
Mobile Project Manager function needs to create a file for users to download

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#2610]
Per the scope of work, the system needs to:
- Create a “Project File” that includes the spatial extent, project duration, team members, and resource data entry forms needed to support a field data collection effort.

- Publish the Project File so that users can download the file to their Arches Mobile Application and begin collecting data.

There are several outstanding questions that need to be resolved:
1. **Is the list of resource instances that are defined as being part of a project static, or dynamic?**  
For example if we are using a spatial extent to define resources that need to be downloaded on the mobile device would we simply take a snapshot of resource instances that fit that criteria during project creation, or would that list be dynamically populated at the time a users downloads the project to their mobile device.
2. I would assume a single(compressed) file for download that includes some kind of manifest.
3. Including team members in the download seems unnecessary and a potential privacy issue
4. Is the file created simply by activating the project or is there a separate method to create the file?
5. What about file versioning?
6.

**Comment by robgaston** [comment]
This may be in some ways related to the way that we implement syncing data w/ the mobile device.

That is, I imagine the project information may be packaged w/in whatever mechanism we use for syncing data to mobile devices (CouchDB or otherwise).  This is important because an administrator could change the project settings (such as the end date or the active state) and I think that we would want these changes to automatically flow to client mobile devices.

I think we should not implement this as a static file on disk, as this would be difficult to maintain and to sync changes made by an admin to the project to devices.

**Comment by apeters** [comment]
That is true, we could instead have all project settings that we currently store in Postgres accessible by the mobile device and business data available in our staging location.  

What about thesaurus entries?  Are those dynamically packaged on every request?  That could be expensive.  In that case I'd want to package that in a form that's readily consumable.  Maybe we just copy those over the staging location as well.

**Comment by apeters** [comment]
I think this ticket will require a discussion before anyone can proceed with it.
There are several use cases that need to be explored before some decisions can be made.

**Comment by apeters** [comment]
I think this ticket is outdated now
