### ISSUE TITLE
Devise a workflow and architecture to to support data QA from within the system

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#2627]
Initially this QA workflow will be required to support data creation from within the Mobile Data App, but eventually be used by web users as well.

- The QA workflow will need to stage or flag incoming tiles as needing QA.  
- Certain users can bypass this and have the tiles they submit go directly to production
- Tiles needing QA will need to be easily discovered (along with the resource instances they are part of) 
- Tiles needing QA will (presumably) need to be presented alongside tiles that are currently in production to assist in the QA process (this is debatable)
-

**Comment by apeters** [comment]
@dwuthrich how will we identify users that will require further QA of their submitted tiles?  Will it just be a special group that if a user is part of will require tiles submitted by the user to be put into a QA queue?

**Comment by chiatt** [comment]
Based on discussions with @dwuthrich and @apeters:

A couple of paths forward: 

- The first would be to build the QA process for the web app first, relying entirely on Django, and then pull in provisional data from couch once data is available from the mobile app.
- The second would be to workout the details of syncing data with couch, after data is available from the mobile app, and then use that knowledge to potentially leverage couch to store all provisional data.

Process (If we do not use couch to store all provisional data):

- All tiles - provisional and non provisional will be stored in the tiles table so that they have the same schema and methods as an approved tile.
- Provisional tiles will be identified in the system as provisional by a foreign key (one to one relationship) to a TileEdit record.
    - A TileEdit record will store the metadata (editor, timestamp, status, type of edit, source tileid) of the provisional tile.
    - The TileEdit record will persist after the provisional tiles are deleted.
    - A source tile (a non-provisional tile) will be allowed to have multiple provisional tiles. The tile visible to users in the resource editor will be the most recent provisional tile with an indication in the UI that the tile is under review.
    - Provisional tiles will not be available in search.
- A resource instance is provisional if all its tiles are provisional. Once one of its tiles is approved, its provisional status will be false.
    - Because provisional resource instances will not be indexed in ES, so we could just check if a resource instance exists in ES to determine if it's provisional or not.
    - An alternative way to check for provisional status of an instance, but probably slower, would be a db query to check if all of its tiles are provisional.
    - A 'provisional' boolean flag could be added to the resource instance model, but that would be difficult to maintain for API users.

- Users that belong to the QAEditor group:
    - When creating a new tile or editing an existing tile - their tile is saved as approved - even if the tile is provisional.
    - If they delete a tile, that tile is permanently deleted.

- Users that are not QAEditors:
    - When creating a new tile - a provisional tile is created with a corresponding TileEdit Record.
    - Upon opening the resource editor, they will see and edit only the most recent provisional tile.
    - If another user opens the instance in the resource editor, they will see the most recent provisional tile and if they make a change, another provisional tile and corresponding tile edit record will be saved.
    - If either user deletes a tile (either source or provisional) that tile will not be visible to any user in the resource editor, however, a provisional tile and tile edit record will be created so that a QAEditor can review the deletion.


Model Changes:

- TileEdit:
    - sourcetile - the tileid of the tile from which a provisional was derived (null if the provisional is a new tile)
    - editor - the user that made the tile edits
    - created - the time the provisional tile was created
    - deleted - the time the provisional tile was deleted
    - approved - true if the provisional tile has been merged with the approved tile
    - targettilediff - difference between the approved tile and the provisional tile. This is may necessary in case an editor wants back out of a merge
    - edittype - deleted, created, updated

- TileModel
    - needs a new column, 'provisional' which stores the foreign key to a provisional tile's record in the ProvisionalModel table.

- Tile proxy model:
    - Needs a new method to reconcile provisional tiles with their respective approved tiles.
    - The save method needs to verify if a user has privileges to bypass the QA process and save their edits directly as approved tiles. Otherwise, it should create a new provisional tile and tile edit record.

- Resource instance model:
    - Needs a new column 'provisional' which stores a boolean flag - true if the instance has no tiles or only provisional tiles. The problem with using this flag is managing it in applications designed with the API.

Group Changes:
- Add "QAEditor" to identifying users that can bypass the approval process and can approve provisional tiles 

UI:
- An interface will need to be developed to display to the QAEditor provisional tiles and their corresponding tile edit data and allow the editor to approve/discard provisional tiles.

**Comment by apeters** [comment]
meets requirements
