### ISSUE TITLE
Allow registration of functions, datatypes and widgets with a predefined uuid.

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#2637]
When registering custom functions, Arches developers will need to be able to specify the UUID of their function to match the ID saved to any resource model that relies (or will rely) on that function. The same is true for custom widgets.

**Comment by mradamcox** [comment]
+1 on this, because not having this ability means that packages are fundamentally broken and unusable in the way they are intended.

Example: I have a custom function. I build a resource model that uses this function. It is now impossible to script the loading (for example, use the built-in `packages -o load_package` command)  of that resource model into a new database. The work around is 1) make sure that the function is _not_ associated with the resource model when you export the resource model (this could be done by manual editing the .json file after export has happened. 2) To reinstall the package (say, from development environment to production environment) start by registering the function 3) now load the resource model 4) in the UI, associate the function with the resource model.

As @chiatt noted above, the same would be necessary if you wanted to have a custom widget used in your resource model.

**Comment by chiatt** [comment]
Works as expected
