### ISSUE TITLE
Advanced Search: filter criteria are not removed when refreshing browser

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#2851]
### User Story

Adding an advanced search criteria then refreshing the browser does not remove the advanced search criteria, potentially miss-representing how many resources are displayed to a user.

Arches should automatically remove any advanced search criteria if the user refreshes their browser

**Comment by robgaston** [comment]
@dwuthrich this is caused by the storing of search queries in the page's URL (querystring).

Since none of the other filters are removed on refresh, I think that rather than removing these on refresh, we should make it clear to the user that there is an advanced search filter being applied.  In the case of our other filters, we do this by adding an item to the filter dropdown indicating that another type of filter is applied.

I think that we should prefer adding such an item to the search dropdown indicate that an advanced search filter has been applied, rather than completely removing the filters on refresh.

**Comment by chiatt** [comment]
There is now an Advanced Search filter tag added, and a user can easily clear the advanced search by removing the tag.
