### ISSUE TITLE
Decide whether or not to use pattern for managing resource crud with configuration manager page

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#296]
The configuration manager uses the same ui pattern of forms, cards, and widgets for managing it's settings as will the resource manager.

The question is, because of this, should we use the same pattern on the back-end (ie: create an admin graph and create forms, and cards and widgets) to manage the data, or should we take a much more traditional approach and create hard-coded forms instead.

Present the pros and cons within this ticket and suggest a solution.

**Comment by apeters** [comment]
I recommend that we use a traditional approach to managing the config data (dedicated html and json).  I don't recommend that we create a graph and forms and cards to do this.

The biggest argument for not using our graph infrastructure is that the backend store is the settings.py file and not the db.  We wouldn't be able to use the same end points for managing the data as we would for graph based forms and this might end up causing more confusion.

**Comment by mradamcox** [comment]
Hi Alexei, I don't have the knowledge or experience with the new configuration manager system (cards, etc.) to give good feedback on this question (so I didn't) but would just like to say thanks for putting the ticket up here because it's helpful to get more insight into the current development of v4.
