### ISSUE TITLE
Re-evaluate usage of .arches file

### ISSUE THREAD

**Issue by ryan86** [archesproject/arches#301]

**Comment by mradamcox** [comment]
It looks like the decision has been made already to deprecate the .arches format https://github.com/archesproject/arches/wiki/Import-Export, but I can't comment on the wiki page (any ideas on how best to do that?) so I'll put some feedback here.

Sounds good.  It makes sense to use the JSON that's behind the scenes anyway.  Regarding support for labels, I did this a while ago with the arc2arches toolbox, and reused the functions recently for some  other data conversion.  I'd be happy to upload them somewhere if that's possible.  They are designed to have the authority files directory and resource graph directory as inputs.  I assume this would be replaced by a reference straight to the db itself.

As for the flat file conversion, I assume this would still require a .config file, or some other field mapping, so, just curious your thoughts on that.  I had to modify the shapefile .config file like so https://github.com/mradamcox/arc2arches/blob/master/examples/data/bldg_points.conflig, because it originally had no way to support node groupings.

**Comment by dwuthrich** [comment]
Adam,
Thanks for the feedback and pointer to your repo.  You're correct that we'll still be using a config file to define the mapping between source file and target resource graph nodes.  Thanks also for the reminder that arc2arches supports import of labels.  I'm sure that Alexei would be able to let you know how to best upload your code.
