### ISSUE TITLE
Move documentation to a new repo

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3104]
We should be able to maintain edit history.
https://mattsch.com/2015/06/19/move-directory-from-one-repository-to-another-preserving-history/

**Comment by mradamcox** [comment]
Docs now stored in archesproject/arches-docs.

All versions of Arches documentation are in that repo in different branches, so version specific updates can by just pushing to the appropriate branch.

All of our previous readthedocs projects now build from that repo:
arches.readthedocs.io
arches4.readthedocs.io
arches3.readthedocs.io (the root url of which points directly to arches3.readthedocs.io/en/3.1.2)

From here on out, we should only link people to arches.readthedocs.io.

**Comment by mradamcox** [comment]
For posterity, here's the git process I used to split the docs into different branches for each version and retain all of the edit history.

1. new empty repo was made, archesproject/arches-docs

2. local clone was made of the main arches repo

3. fetch all branches and then remote origin was removed

```
git fetch --all
git remote rm origin
```

4. delete all tags

```
git tag | xargs git tag -d

Deleted tag '3.0.0' (was efc3e22)
Deleted tag '3.0.0rc12' (was e3868e4)
Deleted tag '3.0.1' (was 766a340)
Deleted tag '3.0.2' (was 582b93c)
Deleted tag '3.0.3' (was bee2d0b)
Deleted tag '3.0.4' (was 4bc4c28)
Deleted tag '3.0.5' (was f3114c3)
Deleted tag '3.1.0' (was 4627ed1)
Deleted tag '3.1.1' (was b78e753)
Deleted tag '3.1.2' (was fc876f0)
Deleted tag '4.0.0' (was 22f490d)
Deleted tag '4.0.1' (was d84b05e)
Deleted tag '4.0b1' (was 2865872)
Deleted tag '4.0b2' (was 31126c4)
Deleted tag '4.0b3' (was a854725)
Deleted tag '4.1.0' (was be70e55)
```

5. make a new branch for each tag needed, pointing to the commit that the tag used to be pointed at.

for example, to make the 4.0.1 branch:

```   
git checkout -b 4.0.1 d84b05e
```

this was done for 4.1.0, 4.0.0, and 4.0.1

for the 3.1.2 branch the tag was not used (because docs updates had happened since that release), instead

```
git checkout stable/3.x
git checkout -b 3.1.2
```

6. now filter out only the docs directory in each new release branch (also master). this was done with these two magic commands:

```
git filter-branch -f --subdirectory-filter docs --prune-empty --parent-filter     'sed "s/-p //g" | xargs -r git show-branch --independent | sed "s/\</-p /g"'

git filter-branch -f --index-filter '
    git ls-files -sz | 
    perl -0pe "s{\t}{\tdocs/}" |
    GIT_INDEX_FILE=$GIT_INDEX_FILE.new \
        git update-index --clear -z --index-info &&
        mv "$GIT_INDEX_FILE.new" "$GIT_INDEX_FILE"
' HEAD
```

7. enter each branch, and do some tidying up. in some, all of the images needed to be migrated from the main arches code. in all, the conf.py file needed to be updated.

make sure each branch's docs build without Sphinx errors

8. add the new empty repo from step one as the origin remote.

```
git remote add origin https://github.com/archesproject/arches-docs
```

9. push everything!!

```
git push --all
```
