### ISSUE TITLE
Make the left nav bar resizable.

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3222]
Users should be able toggle the left nav to expand/collapse it.

![screen shot 2018-04-11 at 3 21 15 pm](https://user-images.githubusercontent.com/823773/38646250-0af6f1bc-3d9c-11e8-8f0e-75b21ecb6ead.png)

**Comment by apeters** [comment]
I'm now seeing resource instance names in the view (see below).  Look under `Assets` and `DISCO Project`

![screen shot 2018-05-18 at 2 32 48 pm](https://user-images.githubusercontent.com/823773/40259001-887d3794-5aa8-11e8-86d7-d08ef7dd1c23.png)

**Comment by robgaston** [comment]
@apeters I've not seen this - can you describe steps to recreate?

**Comment by robgaston** [comment]
<img width="216" alt="screen shot 2018-05-18 at 2 49 21 pm" src="https://user-images.githubusercontent.com/1187406/40259380-adf0248a-5aaa-11e8-91e6-90f38c8409e4.png">

**Comment by robgaston** [comment]
@apeters are you sure that those are not actually resource models (rather than instances)?

It would appear from your screen capture attached to #3209 that at least "TEST" is a resource model, and not an instance, so it's appearance above is expected and correct.  It seems possible that is true for all of the list items that you've referred to above.

**Comment by apeters** [comment]
@robgaston you're right, I didn't recognize them.  The issue with those graphs, is that they don't have an icon associated with them.  We should use the same`?` icon that we use by default in other areas of the app.

**Comment by robgaston** [comment]
@apeters I merged in a fix for the missing icons here #3422

**Comment by apeters** [comment]
awesome!
