### ISSUE TITLE
Saved Searches are called "Saved Saved Searches" in the System Setting tab

### ISSUE THREAD

**Issue by ajwuthrich** [archesproject/arches#3280]
@ajwuthrich commented on [Mon Apr 30 2018](https://github.com/archesproject/disco-data-pkg/issues/9)

The word "saved" is duplicated in the Saved Searches card title.

![Screen Shot 2018-04-30 at 2.43.39 PM.png](https://images.zenhubusercontent.com/5ae784c04b5806bc2bd13b56/b6d57b94-2450-4a0d-a518-0e87065ab27a)

**Comment by mradamcox** [comment]
@ajwuthrich I don't know that this is really a bug, as it's more of just a funny coincidence of terminology. Because the system settings are actually stored as a Resource Instance in the database, they use the same card infrastructure/data input forms as normal resources. In this case there is a node or card named "Saved Searches", just as in other cases there may be a node/card called "Name". So where Name would result in something like "Saved Names", in your example you get Saved Saved Searches.

I recommend closing this ticket because, even if it looks a little funny, the verbiage is actually correct (it is a list of saved Saved Searches) and Arches is functioning correctly.

**Comment by chiatt** [comment]
Though it is functioning correctly I think we should still do something so that it doesn't look strange or unclear. That may mean simply modifying the card title in the system settings.
