### ISSUE TITLE
Create method for contextual/nodegroup level business data validation

### ISSUE THREAD

**Issue by ryan86** [archesproject/arches#3336]
Currently, business data validation is mainly based on the data type of the incoming business data. In some cases a user may want to create business data validation based on contextual knowledge of their resource model. The classic example of this is validating that the start date of an event is less than the end date, thus the value of the start date node is less than the value of the end date node in an instance of a resource model.

One proposed solution to this issue is creating and saving validation routines at the nodegroup level. In this case the validation could be saved in the nodegroup config object.

#### Definition of Done
The ability to define and save contextual validation for a given resource model.

**Comment by robgaston** [comment]
I wonder if this is not better handled at the datatype level.   I don't necessarily see the need to add some nodegroup level machinery for the use case that is described above.  

Currently we have min and max date values stored as static dates in the date datatype configuration.  It seems to me, that we could just as easily allow these values to be defined as a reference to another date node in the current card.

This seems like a more desirable solution because it provides a mechanism (one we already have in place) for respecting these configurations on both the front and back end.

**Comment by ryan86** [comment]
If you implemented this at the datatype level, wouldn't it apply to all business data of that datatype across all resource models?

**Comment by robgaston** [comment]
@ryan86 the logic would reside on the datatype class (where we currently apply validation), but it would use configurations that are applied to the node (which is where datatype configurations are stored), so I don't think that will be a problem.

**Comment by robgaston** [comment]
looking at `datatypes.py`, it appears that our `validate` method would need to be modified to accept either the node or node identifier being validated (currently it doesn't have that as an argument) in order to support this.  I think that this would be a good enhancement to our validation method as it would provide for custom datatype validation logic that uses `node.config`

**Comment by chiatt** [comment]
Couldn't this also just be handled by a custom arches function?
