### ISSUE TITLE
Import limits: geometry too large for single resource

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#340]
I have a very large WKT MULTIPOLYGON for one of my resources.  When I tried to load the .arches file I first got a unicodecsv error, but was able to override it after consulting [this question](http://stackoverflow.com/questions/15063936/csv-error-field-larger-than-field-limit-131072).  Next though, I ran into [this Arches error](https://github.com/archesproject/arches/blob/master/arches/app/utils/data_management/resources/formats/archesfile.py#L203), which uses a 1500 coordinate limit on features (mine was 3390).  I changed the coordinate limit to 4000 and was able to load the resource no problem (in two seconds).  The resource loads to the map view in no time, so...

I'm wondering where the 1500 coordinate limit comes from, and if I will run into trouble down the road.  If not, is it something that should be officially increased?

**Comment by adamlodge** [comment]
Adam,  

The underlying reason for the limit is because Elastic Search has a limit for the number of characters in a given string at 32766.   Further, ES indexes geometries as geojson strings.  We found that with some more complicated geometries (with lots of vertices), that the 32766 character limit was surpassed and resulted in a very cryptic error message coming out of ES.  I think that based on the Historic LA data load, we found that 1500 vertices seemed a reasonable stopping point to force implementors to find ways to reduce the string footprint of their geometries (i.e. simplifying the polygon or reducing precision) in order to prevent the ES error.

It is fair to propose that a better test would be to convert the WKT to geojson and test whether the resulting string exceeds the ES limit. Based on what you have laid out, it sounds like your geometry did not exceed the ES limitation.  This is probably a result of your geometries being of sufficiently rounded precision to not take up as much character space as the HPLA geometries did.

At a minimum, your post serves as a nice workaround to at least try for cases where the initial geometry validation throws this particular error.  If users down the line do try your workaround though, beware that you may see another error come out of ES as the data are indexed.  

Best,
Adam

--  
Adam Lodge
Geospatial Systems Consultant
Farallon Geographics

**Comment by mradamcox** [comment]
Hi Adam, thanks for the info, helps a lot.  Turns out, I hadn't yet added the new resource type (containing the large WKT which is 131000 characters) to the elastic search indexing.  Once I did, I got an error while trying to load the resource with the load_resources command.

So I'll have to do some trimming or something...  Thanks for the help!

**Comment by adamlodge** [comment]
Adam,  

If you’re processing your geometries in Postgis, I recommend using st_snaptogrid to reduce precision.  That way you get to keep all of your vertices and you can cut down on the number of characters by quite a bit.  Failing that, you’ll probably have to simplify the geometry.  

--  
Adam Lodge
Geospatial Systems Consultant
Farallon Geographics

**Comment by mradamcox** [comment]
Thanks for the suggestion, but I'm working with a shapefile that I had QGIS spit out into a csv with wkt. I've been trimming the decimals, but it's still a pain.  I'll probably end up splitting the polygon a couple of times (which won't look great, but I think would be better than removing 3/4 of the vertices).
