### ISSUE TITLE
Add entry in the resource editor tree for related resources and show any related resources under that node

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3604]
![Screen Shot 2018-06-27 at 3.57.18 PM.png](https://images.zenhubusercontent.com/56f071cb6caf56c9d38e0f43/454e483a-f78c-4ac5-9e93-ad5eb46f407a)

**Comment by chiatt** [comment]
@apeters Some resources have hundreds of relationships. For example, the "1:1250 map of Lincoln" bibliographic item in the Lincoln data has 810. In the related resources table and in the d3 graph, we paginate the list of relationships. Should we limit the list of results in the tree to what is visible in the table so that they correspond?

**Comment by chiatt** [comment]
No longer relevant because of the bi-directional relationship implementation
