### ISSUE TITLE
Running setup_db expects PostgreSQL superuser

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches#3719]
**Describe the bug**

When running setup_db on a non superuser, Arches fails to clean the DB before continuing:

https://github.com/archesproject/arches/blob/master/arches/db/install/truncate_db.py#L21
Using `DROP` and `CREATE` for a database requires a superuser.

On a multi-tenancy environment (multiple instances of arches for one PostgreSQL instance), having a superuser's credentials on each arches instance is not best practice.

Changing these commands to ones that do not require a superuser would fix this. Dropping every table in the DB may work.

**Expected behavior**
The ability to run setup_db without having superuser PostgreSQL credentials

**Your Arches Information**

*   Version used: 4.3.x,

**Ticket Background**
*   Found by: @jmunowitch

**Comment by jmunowitch** [comment]
Related to https://github.com/archesproject/arches/issues/2636

**Comment by mradamcox** [comment]
That command actually already does use the Arches-defined username, however, it tries to connect to the `postgres` database, so that may actually be the problem. Not to say that superuser status isn't required by Arches (I believe it is, and probably shouldn't be) but another issue with this command is that it's mixing a username and a database name.

**Comment by mradamcox** [comment]
This is now fixed, in `master` and in `stable/4.4.x`.
