### ISSUE TITLE
Card Manager - Node config edits trigger dirty state of the “Graph” and "Card"

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3790]
Some node configs are presented on the Card Manager as well as the Graph Manager.  Edits to those configs trigger a dirty state on both the Card Manager and Graph Manager.  It might be unclear to the user to check the Graph Manager after editing one of those node properties while in the Card Manager.  Edits could be lost because of this.

http://recordit.co/RfLhKGNf8v
http://recordit.co/TCMWT4yzFy

**Comment by chiatt** [comment]
Managing both the graph dirty state and the card dirty state while in the card manager would require a lot of effort to properly implement  (perhaps a day or more).  Instead, it makes more sense to remove the node configs from the card/widget manager. Doing so would offer the following benefits:

- The solution is faster to implement and easier to maintain in the long run.
- The original reason why the node configs were in the card manager was because in version <= 4.2
 the Graph Manager and Card Manager were separate pages, so it was inconvenient to move between them. Now they are on the same page reducing that barrier. 
- With the linkage between the selected graph and card objects within the graph and card trees makes  moving between node configs and card configs is very easy.
- Editing the node configs only in the node config form may reduce confusion for users as they 
 move from the graph manager to the card manager.

**Comment by apeters** [comment]
meets requirements
