### ISSUE TITLE
Enable cardinality switch on leaf nodes

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#3832]
It is currently impossible to set the cardinality flag, via a "Allow multiple values" toggle, on leaf nodes in the Card Manager.

Per #3780, cardinality is moving to the Graph Manager. It should also be enabled on all of the nodes, not just card-generating nodes.

For example, a Person might have multiple names, each of which might have multiple types. I could be "Rob Sanderson", which is both a personal name and a preferred name, as well as "azaroth42" which is an online handle, but not preferred for addressing me in a UI.

Screenshot:
![screen shot 2018-08-06 at 3 28 06 pm](https://user-images.githubusercontent.com/871868/43744521-3ba9757e-998f-11e8-9f6c-7c7f168d6a36.png)

**Comment by adamlodge** [comment]
@azaroth42  Cardinality (as Arches defines it) is applied only at the card/nodegroup level. If you want multiple values associated to a leaf (which is often a member of a group), that is usually a job for a *-list data type.  For example, concept-list.  

To your example, you could do the following:
- set cardinality to n at the semantic "Name" node
- set Type to concept-list data type (rather than concept)
- enter "Rob Sanderson" as your name under label
- capture two types (you can do that with concept-list), one for "preferred name", and the other for "personal name"
- save record

Now, because cardinality is n at the Name level, you can capture another record that associates "azaroth42" with "online handle" as a separate record.  Further each name is properly associated with its respective set of relevant concepts.

**Comment by azaroth42** [comment]
Could we have a cheat for newbie data modelers that switches to from concept to concept-list (and similar foo to foo-list) in the same slot as the allow multiple values toggle?  Or is this really semantic-list as a datatype?

**Comment by mradamcox** [comment]
The only instance in which I can see this being useful is in the case of string datatypes. Currently there is no way to have multiple of that datatype within a single card, correct?

**Comment by robgaston** [comment]
@mradamcox the way to achieve what you are describing would be through the development of a data type and widget (“string-list” or some such thing....). The use case for this is not obvious to me (a user can enter a list of things in a string, right?), but it could, of course, be done.

IMHO we should close this out, as you can handle for multiple values at the data type level as needed.

**Comment by azaroth42** [comment]
Agree close.
