### ISSUE TITLE
Datatype can't be edited 

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#3887]
At some point during graph creation, I couldn't edit the datatype of any node except the most leaf node

Please check other out-dated constraints (front end and back end and make tickets as necessary)

[https://app.zenhub.com/files/49451058/c9e94595-3329-4d22-b126-5281f06680f7/download](https://app.zenhub.com/files/49451058/c9e94595-3329-4d22-b126-5281f06680f7/download)

![Screen Shot 2018-08-13 at 2.18.20 PM.png](https://images.zenhubusercontent.com/56f071cb6caf56c9d38e0f43/ce9600af-0e1d-46fa-9458-723b057f94a9)

**Comment by robgaston** [comment]
I think this is due to outdated restrictions put on which nodes could have datatypes that collect data; previously any node in a group that was a "card container" could not collect data.  With the new UI, I think we can relax this constraint so that any node my have any datatype (with the exception of the root node of resource models [**not** branches], which can never collect data).

**Comment by robgaston** [comment]
related to #3010

**Comment by azaroth42** [comment]
+1 to this issue. I have run into it once in recent days, but couldn't reproduce it.

**Comment by jmunowitch** [comment]
Reviewed and looks good.
