### ISSUE TITLE
Allow admins to assign groups to users with editing permissions more restricted than the Resource Editor group

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#3911]
Currently if a user can edit any resource they must belong to the Resource Editor group (per https://github.com/archesproject/arches/commit/620847df65ed730715e990eb029e45687db87bfd). 
This requirement means that users must share the nodegroup level permissions of the resource editor group to edit any data in any nodegroup. Admins however may want to give some users more restricted editing permissions than the resource editor. Crowdsource editors, for example, may need more restricted nodegroup permissions.

Perhaps rather than requiring that editors belong to the resource editor group, we simply check if they have a Django permission to edit tiles.

**Comment by robgaston** [comment]
@chiatt it looks like this was caused by a change that @apeters made recently: https://github.com/archesproject/arches/commit/620847df65ed730715e990eb029e45687db87bfd

@apeters I was going to just removed that part of the conditional here (remove `and user.groups.filter(name='Resource Editor').exists()`), but I saw that you just recently made that change, so I wanted to check w/ you first
