### ISSUE TITLE
Safari issue - ordering of widgets not honored

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#4028]
**Describe the bug**
See attached screenshot.  Firefox on the upper left and Chrome on the lower middle, and Safari on the upper right.  Note that Safari's rendering of the string widgets is ordered differently.

![widget ordering issue](https://user-images.githubusercontent.com/9683819/44686868-6cfe5b00-aa04-11e8-9877-95232fb5b627.png)

**Comment by robgaston** [comment]
@adamlodge potentially stupid question: could this be because the safari page was loaded before the changes were applied?  when changes are made in another browser session there is no attempt by the backend to "push" these changes to clients, so they would not show up in the browser until the page was refreshed

**Comment by adamlodge** [comment]
I dont think that that is whats going on. I loaded the the model from the test package and never modified it in the UI.  I was looking at the same arches server simultaneously from all of the browsers.

**Comment by chiatt** [comment]
@adamlodge I just looked at a graph in arches-her and the order in Safari matches Chrome. Can you check and see if you're still seeing this issue.
