### ISSUE TITLE
Order of cards in editor does not follow order of cards in designer

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#4188]
In the graph designer, I reorder the widgets in a card to the order I want them to be in -- in particular, with the value at the top as the required field.

The designer thus has Value, Label, Language, Classification:

![screen shot 2018-10-12 at 3 45 39 pm](https://user-images.githubusercontent.com/871868/46897152-ec6daf80-ce35-11e8-8867-258f69cecc54.png)

However in the data editor UI, the order is not as above. Here it's Language, value, label, classification, resulting in Language being the node selected for the menu on the left rather than value.

![screen shot 2018-10-12 at 3 47 08 pm](https://user-images.githubusercontent.com/871868/46897196-2c349700-ce36-11e8-88bb-45edd4f11b08.png)

Expected behavior:

The order in the editor would be the same as the order in the designer.

**Comment by adamlodge** [comment]
@azaroth42 I am pretty sure that this is another symptom of the same problem underlying #3892. Once 3892 is resolved, could you test this and close out if it is resolved?

**Comment by azaroth42** [comment]
Sure! 

[...]

*nervous look* 

Does that imply that the layout is disconnected due to the integrity error and to reconnect I'll have to rebuild all my models /again/?

**Comment by adamlodge** [comment]
You wont have to rebuild your models, but you may need to revisit your card layouts.

**Comment by adamlodge** [comment]
OK - so this issue is not related to #3892.  However...

I can see that editing the order of widgets within a card is reflected in the cards_x_nodes_x_widgets.sortorder value in the db.  But, when I reload the page, it does not honor the said sortorder value.  Screenshot below shows the ordering as defined in the db with ordering as presented in UI:

<img width="2529" alt="screen shot 2018-10-15 at 4 06 11 pm" src="https://user-images.githubusercontent.com/9683819/46983252-731fc800-d094-11e8-927b-41990055d90f.png">

The two need to be synchronized.

**Comment by azaroth42** [comment]
Fixed by 4197

**Comment by chiatt** [comment]
As @adamlodge has observed, in the case where a branch has a node between two nodegroups, the sort order is not preserved on reload.

**Comment by adamlodge** [comment]
Looking good.  Closing the ticket.  I'll make sure we test this for regression in our releases.
