### ISSUE TITLE
Unexpected results when specifying data for download in the MSM

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#4268]
It appears that the mobile app does not list downloaded data for review if the downloaded data include instances of a model that is not included in the "new" tab of a project 

Steps to reproduce (using the lincoln_release package):

1. Set up a mobile project with the Arches MSM.  Select several forms from a Monument model
2. Allow users to download data, and click on the Monument model and the Activities model
3. Complete the survey definition
4. Open mobile app, synch the newly created project
5. Note that data Activity data have been downloaded and display on the map, but no instances of any kind appear in the Review tab of the project

**Comment by chiatt** [comment]
It is now by design that resources a user is allowed to review must all belong to one of the resource types that a user can create under the 'new' tab of the mobile app. Also, resource displayed in the project map are now derived from tiles downloaded and created on the app, so they should correspond to the data downloaded with the project.

**Comment by dwuthrich** [comment]
meets requirement
