### ISSUE TITLE
change "required" nodes to "not null" 

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#4385]
Documenting some thinking about the true meaning of ""Required" when configuring individual nodes in a card/resource model.  

It seems to me that what we really mean is that if you are going to save a tile of data from the given card, then this particular node cannot be null.  I would suggest we modify the verbiage to "not null" rather than "required".  

Part of what I like about this is that it is consistent with typical RDBMS verbiage.  You are essentially setting a not null constraint on that node in the resource model. 

This change would go hand in hand with #4375

**Comment by chiatt** [comment]
I like the idea of being consistent with RDBMS terms, but `not null` wouldn't be accurate because a geojson object with no features would still be 'required'. The same should be true for strings. You might store a string that has an object in the tile like so: `{'en': ''}`. It's technically not `null`, but you users should still be required to save a string value in order to save the card.
