### ISSUE TITLE
A mobile survey that has expired should be flagged. 

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#4394]
You shouldn't be able to activate a Mobile Survey with begin and end dates that fall outside of the current date.
Also, a Mobile Survey that has expired should be flagged as well.

**Comment by apeters** [comment]
@chiatt When changing an end date so that it falls on a day earlier then today, the system shows a warning that you're deactivating the survey (which is correct), but when I subsequently change that date to a date after today, the system still flags the survey as being deactivated.

**Comment by chiatt** [comment]
@apeters If a survey is made inactive because a user changes the survey settings in a way that deactivates it, we don't reactivate if for them. It has to be manually activated (or maybe a user could discard edits if the survey was active when it was loaded). This is because even if a survey is valid and complete, a user can leave it in an inactive state. I can see that it would be helpful to reactivate a survey after a user updates the project end date, but we would have to know how that situation differs from somebody simply deactivating a valid and complete survey.  Unfortunately we don't track why a survey is deactivated to know when to reactivate it on their behalf.
