### ISSUE TITLE
Ontology Documentation is incomplete and CLI response incorrect

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#4468]
The [online documentation](https://arches.readthedocs.io/en/stable/command-line-reference/#ontology-commands) for `load_ontology` is wrong:

* It specifies -v _n_, when it should be -vn
* It is missing the long form `--vernum`
* It is missing the `-n` / `--name` parameter (which @apeters mentioned, but doesn't work for me)
* It is missing the `-id` param description

Also, the CLI response to `load_ontology` is also wrong

```
(ENV) [rsanderson@GT26940 arches (master)]$ python manage.py load_ontology
You must supply a version number using the -vn/--version argument.
```

* Should be `--vernum n` and `-vn n`, as above

Compare with the response to `load_ontology -h` which gives the right parameters.

**Comment by mradamcox** [comment]
@azaroth42 Would you mind making a ticket in the https://github.com/archesproject/arches-docs repo to mirror the RTD docs portion of what you're talking about here? To that point, in fact -vn is what we have in the docs, but due to an unfortunate formatting issue (mostly because Arches uses non-standard, two-letter abbreviations in command line arguments) the second letter is italicized, which is annoying. I've looked at other formatting options for the argument lists in that section, and hopefully we can fix that up eventually. You're correct that the long-form argument is missing, that's an oversight on our part.

**Comment by azaroth42** [comment]
Done --> arches-docs#89

**Comment by mradamcox** [comment]
Thanks!
