### ISSUE TITLE
Improve the package/project process

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#4769]
It would be nice to simplify the development process and streamline the way packages and projects interact.
Maybe packages could be Django apps, which then could be pip installed and would allow for migrations to be utilized.

**Comment by chiatt** [comment]
We have changed the package load process so that extensions are loaded first from the project, and then from the package. An extension is only copied from the package to the project if it does not already exist in the project. This prevents the developer from overwriting work in the project with old extension files in the package if the developer absentmindedly loads the package without having first moved their files from the project to the package.

**Comment by apeters** [comment]
confirmed this behaviour in the latest
