### ISSUE TITLE
improve process around template package.json ("numeral.js" omitted)

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#4841]
**Describe the bug**
I didn't personally encounter this issue, but I'd like to make a ticket to cover what the original poster described in this Arches user forum post:

https://groups.google.com/forum/#!topic/archesproject/-wQtuXjTlfk

She was getting a 404 on numeral.js when trying to view Arches using the dev server. It sounds like yarn was properly installed and all of the other npm packages had been installed correctly, but there was just some issue with numeral.js.

After she ran

    npm install numeral

everything worked fine.

**To Address**
In my opinion, it would be sufficient to run a few fresh installs of Arches on to ubuntu machines (16.04 and 18.04) and pay extra attention to numeral.js. Also maybe do a little research on that library and see if anything has changed about it (new version, etc) recently. It's possible there was something strange in her environment that caused this issue, but it's definitely worth checking out.

**Your Arches Information**

*   Version used: 4.4.1
*   Operating System and version (desktop or mobile): Ubuntu 16.04
*   Browser Name and version: n/a

**Comment by robgaston** [comment]
@mradamcox I think that numeral.js itself here is a red herring - this issue is likely because the package was installed but the template `package.json` was not updated, see:
https://github.com/archesproject/arches/blob/master/package.json
https://github.com/archesproject/arches/blob/master/arches/install/arches-templates/project_name/package.json

We could simply add this package to the template, but I would argue that this really just works around a process issue that has been exposed here...

@chiatt is there any reason that we can't just copy the regular `package.json` when creating a project from the template, thus obviating the need for dual entry of newly installed packages?

**Comment by mradamcox** [comment]
Thanks a bunch @robgaston. Is this related at all to https://github.com/archesproject/arches-docs/issues/61, or is it just something that needs to be updated in core arches code?

**Comment by robgaston** [comment]
@mradamcox documentation could help here, but really I'm looking to improve the process by obviating the need to manually copy anything.  A developer ought to be able to add a dependency w/ `yarn install {package name}` and not have to do anything else, as this is what any outside yarn user would expect.

It seems to me like package.json in the root and in the template should always be identical, so I'm guessing we can just copy that file as part of the project creation script rather than including it in the template which requires additional action on the developer's part which is not at all obvious currently (and is how the issue w numeral.js arose in the first place).

**Comment by mradamcox** [comment]
Ok great, that clearly answers what I was wondering about. Thanks!

**Comment by mradamcox** [comment]
So at this point, this ticket should definitely be addressed before that documentation ticket.

**Comment by chiatt** [comment]
@mradamcox I moved the package.json file from root to `/arches/install`. This won't change anything for people working out of an arches project, but if a developer wants to install/add js dependencies directly in arches, the will have to run `yarn install` or `add` from `/arches/install` rather than from `/arches`.  I think that just affects the note at the bottom of this page in the docs: https://arches.readthedocs.io/en/stable/creating-a-development-environment/#setting-everything-up

**Comment by robgaston** [comment]
This looks good to me
