### ISSUE TITLE
Review and update dependencies

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#4842]
PyYaml is unused and urllib3 needs to be updated

**Comment by mradamcox** [comment]
For what it's worth I just commented `urllib3` out from requirements.txt and then ran

    cd arches
    pip install -e .
    pip install -r arches/install/requirements.txt
    pip install -r arches/install/requirements_dev.txt

The version of urllib3 that was installed is `1.25.2`

On further investigation, this PR indicates that the version was pinned because of a CI failure. https://github.com/archesproject/arches/pull/4207 looks like it was specifically for CI?

Here's the failed CI test from the PR history that directly precedes the pinning of `urllib3` to `1.23`

https://travis-ci.org/archesproject/arches/builds/442884629?utm_source=github_status&utm_medium=notification

Looks like it was `requests` that didn't support 1.24 at the time

Personally I think it would be preferable to remove it from requirements.txt. It's confusing if it's in there but not directly used in Arches.

**Comment by mradamcox** [comment]
@benosteen reports that Travis builds also work just fine with these two libraries removed from requirements.txt https://travis-ci.org/benosteen/arches/builds/535521352

**Comment by benosteen** [comment]
The diff to master is linked through that travis report, but the key change
I made is just the removal of urllib and pyyaml from requirements.txt (
https://github.com/benosteen/arches/commit/e02a0c05d0ea#diff-556b1c9baefb39f9b9018530c098d2dc
)

I checked its logs and it did run the tests and they passed. (There is also
a change to the .travis.yml that adds an attempt to run the project with
python 3.6, which is optional and currently failing as expected)

Ben

**Comment by mradamcox** [comment]
nice work on the python 3 test, that'll be useful in the upcoming year...

**Comment by chiatt** [comment]
Works as expected
