### ISSUE TITLE
import improvement: disable edit log entries on bulk import

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#5093]
should apply to both csv and json imports

**Comment by mradamcox** [comment]
Could you give your reasoning for this? I think it would be a regression. I have had to rebuild an Arches database from only using the Edit Log entries before, which would obviously be impossible if this ticket were completed. I think some more context here would be very helpful.

**Comment by mradamcox** [comment]
I would also point out that v4 has already introduced regression in bulk import by abandoning the use of the `load_id`. My understanding is that there was no real reason for this, it just kind of happened. So, it would be nice to hear some deliberation about the proposal in this ticket.

**Comment by mradamcox** [comment]
One more thing: I have often thought that a great enhancement would be to add a "username" argument to the bulk load command so user names are recorded in the edit log during that process (instead of the generic ETL name which isn't especially useful). This is something that @reubenosborne1 and I talked about a while ago on Slack, but I guess I never made a ticket about it (can't find it now). Whenever a bulk load UI is introduced in v4, this would be even easier as the user information would be tied to the request already.

**Comment by adamlodge** [comment]
Based on our testing, this will result in cutting import times by about
30%, and we haven't been aware of the value of those logs on import.  We'll
provide more detailed info on our thinking shortly.

**Comment by apeters** [comment]
To be clear @mradamcox, we'll still log the fact that a resource was saved during import, but we won't be logging every tile save during import.

**Comment by mradamcox** [comment]
I'll wait for @adamlodge to add more detailed reasoning before responding to any of this.

**Comment by mradamcox** [comment]
Ok, hours ago @adamlodge told me via slack he had no more to say about this, and no one has given any more insight (and it's the end of the day on Friday) so I'll just post my thoughts now.

@apeters could you point to where the fact that a resource was saved is recorded?

I understand that saving the edit log entries for each tile is pretty cumbersome during a large load. However, to me just losing that information completely is a hugely inappropriate way to handle it for the reasons I described above. That's why I wanted to hear more deliberation about this, what other options had been considered, why it's considered acceptable, etc.

Here are my ideas. They aren't strictly co-dependent, but they could work together.

1. Bulk uploads should be handled as their own objects in the ORM. It's easy to imagine what attributes and methods would be useful for this class. It also would be a perfect backbone for a Bulk Upload Manager, etc.

    class BulkUpload()
        def init():
            sourcefile
            date
            user (linked to Django user as I mentioned above)
            resource count
            errors
            etc.

        def remove()
            removes all resources loaded in this bulk upload

        etc.
  
2. Edit logs could be stored as text files during bulk uploads. I'm not sure what kind of file size this would create, but it's essentially a .arches file a la v3. It would be super easy to write the same contents that gets stored in the edit log to a csv. This file could be linked to the BulkUpload object described above.

3. Alternatively, more creative ways of saving edit log entries could be explored. For example, save resources in chunks of 500, while saving the edit log info to a list, and after each chunk use a separate atomic transaction on that list.

4. Explore improving import speeds in other ways. This is the most obvious of course. I've already worked on implementing support for multiprocessing which cuts load times by (at the very least) 50%. What's currently in Arches is basically a proof of concept; it works, but logging and message reporting is not good. Maybe chunking into sets of 200 and _then_ multiprocessing?

5. At the very, very least, dropping the edit log reporting from bulk upload operations (to get back to the specific point of this ticket) should be an optional _non-default_ argument. Not just baked directly into the existing command behavior.

**Comment by adamlodge** [comment]
Adam C,

A few things...
1> This is just a proposal at this point.

2> Our proposal is to only disable logging of tile edits on import of csv and json files.  We will still log creation of resources and we will continue to log as we always have on normal CRUD operations in the system beyond data import.  If recovery is a concern, can't you just recover from the source file that you loaded in the first place?

3> The log entries that are created on import are quite meaningless.  They capture every single little tile create and many edits that are not instructive on the actual history of human interaction with the resource.

4> We agree that your 5th suggestion would be easy to implement and be a good safety valve in case there really is value in edit log entries for tile-level bulk import operations

**Comment by mradamcox** [comment]
To your points:

1) Ok, that's fine. There's nothing about the ticket to indicate that it is a proposal (no labels were used). Also, you both continue to say "will" instead of "would".

2) As I asked of @apeters, could you point to where the logging of the creation of resources takes place?

    To be clear: Rebuilding the database from the edit log is obviously an absolute last resort and should never be necessary. However, even if all of past input files were easily accessible (ignoring the reality of staff turnover and the difficulty of retaining every single load file from users all over the world over the course of multiple years) then it's still not enough because imported data could contain contextual values, such as date tiles recording the current time, or unique consecutive identifiers (I thought this was a datatype in v4 but can't find it now...). So yeah, it would be great to have all of the input files. But it still may not be enough.

3) Then I suggest making them smaller and more relevant. What I'm gathering is that you want to not record the list of tile values that are saved for a resource on import. I think that list should be retained.

4) Of course. If this is a non-default option, I don't have any problem with it being available, I would just personally never use it and would advise others not to use it. Case closed.

----

To get back to basics, this is a proposal to cut bulk import time by decreasing the integrity of logging actions. That is what I'm objecting to.

**Comment by chiatt** [comment]
completed
