### ISSUE TITLE
swap workflow plugin: init-workflow with active-workflows

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#5258]
in core arches, if consultations project is loaded (or if the workflow plugins are loaded) there's a button in the nav bar for "init-workflow". This should be replaced with "active-consultations" plugin

**Comment by whatisgalen** [comment]
@dwuthrich note that this change requires reloading the package to take effect

**Comment by dwuthrich** [comment]
@whatisgalen Although the link in the vertical menu now displays the proper label, it does not return the user to active consultations in the consultations chrome.

The URL is http://<domain>/plugins/active-consultations instead of what is should be: http://<domain>/consultations/plugins/active-consultations

https://recordit.co/qyGuFQbN8i

**Comment by chiatt** [comment]
@dwuthrich I think this should now be resolved

**Comment by dwuthrich** [comment]
meets requirements
