### ISSUE TITLE
As a Resource Designer, I want to see all graphs associated with my resource and select a specific graph so that I can review/update the configuration of the data entry cards

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#526]
## Definition of Done
- [x] View list of graphs related to a resource (these are presented as cards in the UI mockup)
- [x] Selecting an individual graph takes us to the card configuration page for that card

## Definition of Done
UI supports this workflow

**Comment by apeters** [comment]
There is one difficulty I see with showing a list of graphs related to a resource.
After a graph is appended to a resource there is no reference back to the graph that was appended.  In fact, subsequent to the graph being appended to a resource, that graph could be deleted or completely mutated so that it doesn't resemble the original graph.

**Comment by dwuthrich** [comment]
meets requirements
