### ISSUE TITLE
Search request failed

### ISSUE THREAD

**Issue by ashishnp** [archesproject/arches#5334]
Dear all,

We under Nepal Heritage Documentation Project (NHDP) developed Digital Archieve for Nepalese Arts and Monument (DANAM), http://uni-heidelberg.de/danam/

Arches version is 4.3.3. It was working fine until yesterday. When we wanted to search, the error Search request failed comes. I believe this is because of Elasticsearch. We have not changed anything on the system except to give a new tocken to Mapbox. What might have gone wrong. We can still access data through typing the report url, eg,  http://nhdp.kjc.uni-heidelberg.de/report/a83b5ca2-9d62-11e9-9dd2-0242ac130005.

We are little worried that restarting the docker on which DANAM might create other problems and we might not be able to retreive what we are getting till now.

Any suggestions and help would be much appreciated.

Regards

Ashish

**Comment by benosteen** [comment]
Is the elasticsearch container still running? If not, restarting its
container should get things started and you can investigate why it shut
down in the first place. It is worth switching to use a more resilient
deployment of elasticsearch, rather than the example elasticsearch
container configuration in the default docker-compose. Running a number of
elasticsearch nodes as an external service, separate from Arches, and
remove the elasticsearch container from the docker-compose or
TaskDefinition you are using to run this application.

Ben

**Comment by chiatt** [comment]
@ashishnp I'm going to close this ticket because it seems pretty time sensitive and I'm assuming you have it resolved. If this is still a problem feel free to reopen this issue.
