### ISSUE TITLE
Implement in the UI a way for users to see that they have unread notifications.

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#5562]
There should be a regular request to check the notification status for a user. A django view will be needed to query for unread notifications and to update notifications as read. Ideally the polling frequency (or whether polling would be performed at all) would be configurable by an admin. If a user has unread notifications, they should be notified with an indicator next to their user name in the upper right of the page. This may look similar to how github alerts users to unread notifications. 

 ![Screen Shot 2019-11-14 at 3.06.54 PM.png](https://images.zenhubusercontent.com/57d0a2a4e40e5714b16e73d7/653d574e-a18b-471a-a7c1-4ff9cc491eea)

**Comment by apeters** [comment]
There seems to be a bit of a lag when clicking the download button and getting a notification.
https://recordit.co/mm3a7HjESy

**Comment by whatisgalen** [comment]
@apeters if by lag you mean the total time between clicking "download" and the notification being generated, this is due to the notification not being sent until the zipfile is ready for download. I'm guessing at 14654 resources it might have taken a little longer. Nothing there seems unusual.

The email notification (`templates/email/download_ready_email_notification.htm`) that gets sent (if conditions are met, e.g. email server active and user's email notification settings are set for email) includes a button with a download link so that a user should in fact be able to download from their email. Per your suggestion, it would probably make sense to re-word to "where to send a download link to your results".

Right now, there isn't a cron-job checking for new notifications so the UI will only update on refresh, navigate to new page, or on clicking the notification (bell) icon. A few weeks ago it seemed like this approach would be sufficient but I'm sure we could leverage celerybeat in the near future to have a live update.

**Comment by chiatt** [comment]
@whatisgalen @apeters Is this supposed to be assigned to me?

**Comment by chiatt** [comment]
@apeters It looks like Galen added a loading indicator to the search download button

**Comment by apeters** [comment]
works as expected
