### ISSUE TITLE
Implement UI to perform a search export

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#5564]
The UI should allow a user to select the type of output they want, the output file name (maybe?), and the precision of spatial coordinates.

**Comment by apeters** [comment]
The UI looks good, but when I supplied an email address it just downloaded the data directly.  It wasn't clear when data would be sent via email.
Also, when I first tried, this, I didn't set a fieldname but it saved properly.  The second field that I set for download I did the same (not set a fieldname)  but this time the page hung.  It looks like you can set a single blank field to download and that works.
Also, you can set a semantic field for download and that also works, but returns "None" values.a
Also, this is broken in "consultations" because we've overridden the "search.js" file in that package.

**Comment by apeters** [comment]
looks good
