### ISSUE TITLE
Search Results Export: CSV and Shapefiles do not contain the same data when exporting from the same query

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#5653]
I created a query in lincoln_release that included a spatial filter that returned 5 instances.

CSV export included all 5 instances and all the expected fields
Shapefile export only included 2 instances, did not include all the expected field, and mis-labeled a field name.

To reprodue:
1. Identify nodes in a cardinality-n tile and include them as downloadable.  I selected condition state and date of assessment from Condition Assessment in the Monuments model in lincoln_release 
2. Create a query that includes a instances with multiple condition assessment tiles
3. Download as CSV and note that expected data is included in file
4. Download same query as shapefile and note that not all instances appear, not all fields appear.  In my case, the instance name field was mis-labeled as the condition date

**Comment by apeters** [comment]
this appears to be fixed in the latest
I was able to get the same data when downloading the Lincoln Heritage Asset - Area dataset (note though, that the dataset is a total of 662 records, 20 of which don't have geometry, so the CSV download will have all 662 records, but the shapefile export will have only 642 records).
