### ISSUE TITLE
We should display widget labels in the time search component instead of using node names.

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#5824]
![Screen Shot 2020-01-08 at 12.35.30 PM.png](https://images.zenhubusercontent.com/56f071cb6caf56c9d38e0f43/9168569d-0ebc-4ac6-ad21-df96fa140a3e)

**Comment by whatisgalen** [comment]
Notes on my PR for this ticket:
1. Because there may be multiple different date-type nodes in a graph that use the same widget, I have chosen to concat the widget label with "-" and the node name (for clarity).
2. Because a given datatype might be associated with different widgets for a card, there is some extra querying and logic added in the view to match each node with its specific widget, rather than solely assume based on datatype.

**Comment by apeters** [comment]
looks good
