### ISSUE TITLE
Create a Koop.js service that can serve arches data to an ArcGIS Pro client

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#5870]
From the SOW:
Our software development will start by transforming Arches data into an esri GeoService.  We will use Koop ([https://github.com/koopjs/koop](https://github.com/koopjs/koop)) and Arches’ elastic search engine to support on-the-fly transformation of Arches data into the appropriate GeoService for ArcGIS Pro.

Our approach will allow developers to create an “Arches Data Provider” that publishes esri GeoServices.  The Arches Data Provider can be configured on a model-by-model basis so that developers can specify the exact Arches fields to expose in the GeoService.  Once configured, the Arches Data Provider will publish esri GeoServices that can be accessed by ArcGIS Pro.

This development effort will extend the Arches Platform code base, making it possible for all Arches users to publish data in real-time in a native esri proprietary format.  Esri users will then be able to access and display Arches data (read-only) within ArcGIS Pro and esri’s GIS server products.

**Comment by robgaston** [comment]
@apeters I think this may be in part a duplicate of this ticket (on which much work has already been done): https://github.com/archesproject/arches/issues/5475

There is also a separate repo for the arches koop app here where we should probably be tracking work on this (instead of here in the arches repo): https://github.com/archesproject/arches-koop

**Comment by apeters** [comment]
Yeah, I thought about that after I made this ticket.  Closing this ticket in favor of the one here: https://github.com/archesproject/arches-koop/issues/1
