### ISSUE TITLE
Arches API: support ability for developers to request instance json with node names, concept label disambiguated

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#6030]
Our current API endpoint for resources http://localhost:8000/resources/<instance uuid>?format=json&indent=4 returns json with tile data presented using UUIDs for all node names and concept labels.

Proposal:
Like we do with our geojson endpoint, we should allow developers to request json with human readable names instead of UUIDs.

This would better support many use cases, such as accessing a single resource instance for presentation to a user outside of Arches.

**Comment by chiatt** [comment]
Further discussion is needed on how to adapt this to support more use cases.

**Comment by chrabyrd** [comment]
If anyone has an opinion on how this solution should look, I've drawn up a doc [here](https://gist.github.com/chrabyrd/9f0b31956ba14964976274543d3f34e0) . The purpose of the doc is to drive a discussion ( synchronously or asynchronously ) on the most acceptable path forward. 

Note: In the Project Discussion section, there is a link to a publicly-editable google doc meant to drive asynchronous discussion. If we feel it's better to have a synchronous roundtable instead I'm more than happy to accomodate.

**Comment by dwuthrich** [comment]
There are pros/cons for each approach, but I think the card based solution would be most useful for meeting a high priority use case: allowing a developer to take instance data and use it to integrate with another system or create a custom report

**Comment by apeters** [comment]
@chrabyrd The more I think about this the more I'm leaning toward using the Card model as the basis of the graph shape.  The advantages it has, are more natural graph shape without reliance on using magic strings like @value within nested objects, and json properties that would align with what most users see (widget and card labels).  
At this point I think we should proceed with this goal in mind.

**Comment by chiatt** [comment]
I feel like solution 1 would result in data that is easier to query and verify, and I agree that it would probably be faster to develop with a more flexible outcome (e.g. improved csv export). Also, widget and card labels can easily be changed. If they are, then using solution 2 you could easily break any report or system consuming the data. If the card/widget labels were added to the metadata in solution 1, and human readable nodeids were used as keys (presumably less ephemeral), I think the outcome would be more reliable, more flexible and because it is simpler, could meet it's use case as quickly as solution 2.

**Comment by azaroth42** [comment]
I would also go with the node tree approach, as the card system is more likely to be extended with new UI based improvements that would then cause complications in this more data oriented API structure.  For example, grouping cards ... does the data get duplicated because the sibling cards exist independently as well? Even if they're set to not be visible?

This seems highly related to #6299 ... and a solution there would solve much of the ambiguity problems here, no?

**Comment by azaroth42** [comment]
Some additional possible use cases that this work might facilitate:

* Is this read only, or could it be used for manipulating individual tile data?  (e.g. PUT to it to change just a name value)
* Useful for internal javascript work as well -- e.g. building workflows?
* Useful for more complex descriptor functions to pick the right name / description values?
* Useful for building more complex search result hit lists (e.g. with more than name/description)?
* (Relatedly) Useful for building resource summaries, rather than current from-scratch approach?

**Comment by AJ-HistoricEngland** [comment]
I agree that the node structure be used. Others have already covered my reasons which are:

API is for data so should be closer to the graph.
Cards are more likely to be changed.
Possible future PUT and POST as the format is more understandable to devs without Arches experience.

You may also want to have an `@type` to help describe the node data, but I agree that this might not be necessary initially.

How would semantic nodes be represented?

**Comment by chrabyrd** [comment]
> How would semantic nodes be represented?

Following the same pattern as other nodes:

{
    "Semantic Node" : {
        "@value": null,
        "@node_id": UUID,
        "Child Node": {
            ...
        },
    },
}
`

**Comment by robgaston** [comment]
I don't see any mention of including tile ids in the above propositions, but it would be very difficult to support PUT/POST in the future without these.  It also prevents a programmer from using the existing APIs to update tile data.  Every value should include a node id and a tile id.  This would allow for easy use of existing APIs to update specific values represented in these payloads.

**Comment by apeters** [comment]
I'll have to revise my previous thinking based on the realization that card method would require the locking of card/widget labels which really are meant to mutable during the lifecycle of a graph.  

In that vein, whatever we use for property labels (node name, something else??) will also have to be fixed for the life of the graph once data is collected (or node ids will have to be included in the the payload to resolve changing node labels). 

We might even want to consider the idea of implementing **graph VERSIONING** to handle for graphs that might potentially change over time.

**Comment by azaroth42** [comment]
Does not meet requirements. The issue specifies ?format=json and the implementation replaces the JSON-LD default with JSON, breaking infrastructure, as per #6868.

**Comment by apeters** [comment]
closing this issue.  if there is an issue with how the endpoint is accessed that should be addressed in another ticket.
