### ISSUE TITLE
MapBaseManagerView destroys performance

### ISSUE THREAD

**Issue by azaroth42** [archesproject/arches#6443]
**Describe the bug**

Time to retrieve the the search view with 13M instances is 1.25 seconds (on a not very high spec web box, connecting to remote elastic and postgres) **when MapBaseManagerView is removed from the class hierarchy**.

![Screen Shot 2020-07-23 at 2 17 42 PM](https://user-images.githubusercontent.com/871868/88323510-58aa6200-ccf0-11ea-9142-e53efa6d9c0a.png)

That's not bad for time to first byte.

However... putting MapBaseManagerView back in and changing nothing else ...
wait for it ...
are you ready? ...
it's not pretty, just warning you ...

![Screen Shot 2020-07-23 at 2 26 21 PM](https://user-images.githubusercontent.com/871868/88323619-82fc1f80-ccf0-11ea-834f-04aa421c6f4c.png)

2.2 MINUTES to generate the page and TTFB.

The time is spent walking through the geom_nodes, but the culprit is in get_map_layer()
 
```
        count = models.TileModel.objects.filter(data__has_key=str(node.nodeid)).count()
```

This count takes up all the time.  It can probably be replaced with exists() ?

**To Reproduce**
1. Load 13M objects... ;)
2. ...

**Comment by azaroth42** [comment]
eg:

```
        okay = models.TileModel.objects.filter(data__has_key=str(node.nodeid)).exists()
        if not preview and (not okay or not node.config["layerActivated"]):
            return None
```

**Comment by AJ-HistoricEngland** [comment]
We have not had the opportunity to contribute back yet but we fixed this by adding the nodegroup_id.

Our DB has 15 million rows in the tiles table so you really need to be able to use an index scan rather than a full table scan. We tried `exists()` but it made little difference in general so stuck with `count()` for now.

```py
count = models.TileModel.objects.filter(nodegroup_id=node.nodegroup_id, data__has_key=str(node.nodeid)).count()
if not preview and (count < 1 or not node.config["layerActivated"]):
    return None
```

We will be looking to push back our fixes (done against stable/5.0.x) towards the end of our current project.

In the mean time, please see the following commit in our fork for where we applied the fixes...

https://github.com/archesproject/arches/commit/6e4665a3578e707295f27c5c1d9a1d3bd2c3282e

**Comment by AJ-HistoricEngland** [comment]
See my PR above.  This is against stable/5.0.x as that is what we are using. Not sure if you can cherry pick this into master? I've not tested this on master.

**Comment by chiatt** [comment]
Further improvements to be made under #6534
