### ISSUE TITLE
As a card designer, I want to implement processing functions as part of the CRUD lifecycle for a form instance so that I can automate certain processes

### ISSUE THREAD

**Issue by apeters** [archesproject/arches#672]
For example, as a user I might like to create a geoprocessing function that can take an address as input and populate another card with the addresses geocoding.  This function could get invoked when a user populated the addresses fields.

**The outstanding question are:**
1. How does a card designer register a new processing function with the system?
2. What form does the function take?
3. When in the lifecycle of the CRUD operation does the function get invoked (eg: before save, after save, etc...)?

Some possibilities:
- a user places a python script file to perform the processing in a known location on the server.  The system then reads from that location the list of files and then presents that to the card designer as a list of possible processing functions that can be invoked during CRUD operations on that card type.
- a ui is created that allows a designer to register a function with the system by uploading a processing script to the server. The system then presents that to the card designer as a list of possible processing functions that can be invoked during CRUD operations on that card type.

**Comment by apeters** [comment]
If we use a script file, then we'd probably make a abstract class that developers could inherit from that would define some basic hooks and known endpoints for the system to use.  Scripts could have access to some portion of the graph, or all of it, or more?? and would then have the responsibility to develop the appropriate script.

**Comment by robgaston** [comment]
I think that functions should be defined as an asynchronous javascript function rather than a python script.

This would provide for functions that are purely client-side (if, for example, they just need to do some processing on the current tile data), but also allow for functions that require making calls back to the server.  This would also provide for functions that interact with external services without routing that traffic through the arches server.

If our functions were defined as python scripts, we would always have to issue a call to the server to complete the function call.

The pattern for using the functions would mirror our pattern for loading widgets, in that the database record can contain a pointer to a module which we can use requirejs to load that would return the asynchronous function.

The function would be called with a callback, the tile record (including all data and metadata) and probably the nodeid for the node that the function is attached to.  This way, the function could call back to the server to do operations on the wider graph or other arches data, or operate directly on the tile to retrieve or update other values in the tile.  Upon completion, the function would call the passed in callback function with a success flag so that the form may act accordingly (revert changes, or whatever).

**Comment by robgaston** [comment]
RE: data model - 

We currently have a foreign key to the functions table in both the `cards` and the `cards_x_nodes_x_widgets` tables.  I assume we want to be able to associate functions to both cards and widgets, which this allows for, but in both cases, I think, we need to be able to associate many functions and this model only allows us to associate cards and widgets to a single function.

I'm thinking we should use the column `functiontype` to filter functions that are appropriate for cards vs. ones appropriate for widgets.   Perhaps we should also filter the widget level functions based on datatype.  Therefore, the value in `functiontype` might be either 'card' or a datatype name.

**Comment by apeters** [comment]
I think functions will have to have support for both a client-side component and server-side component.  I can see some functions not needing a client-side component at all and some needing only a client-side component.  I think we should be able to support both.

**Comment by robgaston** [comment]
I agree, which is why I argue the entry point should be a javascript function.  The client script can always issue requests to the server, but the reverse is not possible.

We should have a pattern in place for how the client functions can integrate with the server (I proposed a starting point for this above), but if we want functions to be able to call both javascript (client) and python (server) code, I think that the starting point will have to be a javascript function.

Functions are fundamentally triggered by some user action on the client, so it seems to also make sense that they would start off as javascript functions that would then issue requests to run server side code as needed.  The javascript functions would need to be asynchronous to provide for the ability to make requests to the server.

**Comment by apeters** [comment]
I think I disagree with the assertion that:
> "Functions are fundamentally triggered by some user action on the client

Obviously strictly speaking that is the case, after all we're not talking about something like a cron job here (something that runs independently of user input), but I think some functions could be client-side only, some could be server-side only and some could be both.

An example of a "server-only" side function:
For example upon save I could see a function being needed to perform some geo based calculation.  While strictly speaking this is triggered by the user clicking the save button, this seems to me like the kind of thing that happens during the process of the CRUD lifecycle.  In this scenario there doesn't seem to be the need for an additional client side function (other then an existing save).

An example client-only function:
A user selects a value from a dropdown and the UI changes (eg: tabs are hidden or shown) to reflect that selection.

An example client and server function:
We want to validate an address against an address authority and provide suggested alternate values.
Or while a users is drawing a polygon on a map, we want to present the user with a selection of intersecting resources for them to select from (spatial search if you will).

**Comment by robgaston** [comment]
I agree that server-side only functions may exist (that is, functions that wouldn't by their nature necessitate a client request), but as you acknowledge the use cases we have in front of us are still triggered by a user action ("the user clicking the save button"), at least as far as I know.

I point this out because I suspect it may simplify the implementation if we can define functions as being platform specific (javascript or python).  'Functions' will need to start by running in one of these two environments, and we'll need to support either one or both as an 'entry point' for executing functions (ie arches 'functions' can be specified as python functions, javascript functions, or both). We may be able to take advantage of the fact that we can execute code on both platforms (via requests) to simplify things a bit there and just define functions as being asynchronous javascript functions (stored in the db as a AMD/requirejs path).

I think the downside here would primarily be the additional overhead of client server interaction executing functions before & after save events (where, as you point out, we already have a request occuring).

This all assumes my initial assertion that we don't *need* the capability to run functions via the server without client interaction.

This all makes me wonder about import -- will we need to support execution of functions on import of business data?  If so, the javascript function idea may be moot, but I think we'll also want to consider moving the function associations to the node/nodegroup level (for the same reasons we did so w/ cardinality).

**Comment by apeters** [comment]
My base assumption is that we need the ability to call functions without the direct interaction of the user (you bring up import which is a good example).

Hence, I think there are 2 ways to "trigger" a function:

1. As a direct request from a user (explicit)
2. At a specified time in the CRUD lifecycle (implicit)

The purpose of item 1 above would mainly be to assist the user in making decisions about the data being submitted for persistence to the db.
Eg: 
- it could supply the user with a number of options to pick based on some action by the user
- it could guide the user via the ui into the appropriate form
- it could validate imput by the user
What it absolutely wouldn't do is persist anything to the db

The purpose of item 2 above would mainly be to automatically generate data or events, or validate user input during the CRUD lifecycle.
Eg:
- it could could generate additional data based on user input and the resutls of an external service (eg: milepost calculation)
- it could geoprocess data for use in one tile based on the data submitted in another tile
- it could be used to index additional data into elasticsearch
- it could be used to notify users when specific data get's added/updated/deleted

Item 1 would involve at least a client-side invoked javascript function.  That function could call out to a related server-side python function or not, or some third-party service, or purely be client-side (eg: logic that hides a tab or disables input).

Item 2 would only be a python function (of course that function could itself call other functions or third-party services).  The idea here would be that every python function gets an endpoint so as to be callable from the front end.  You may never use the end-point, but it's there (or maybe you flag the function as needing an endpoint and so one is automatically created).

Functions are stored in the database as dynamically loaded modules, either client-side via requirejs(AMD) as you suggested, or as dynamically loaded python modules.

Our main unit of persistence is a tile, and a tile represents the data attached to nodes in a node group.  It makes sense then that, generally speaking, functions are attached to node groups.  
- Client side functions would clearly have access to the data stored within a node group but may not have access to data in other node groups.  It seems that, most likely, they would generally only concern themselves with data captured within that nodegroup (there are exceptions I'm sure).  
- Python functions are also similarly bound to node groups but in this case are not bound by a UI and could access data in other tiles(nodegoups) and potentially generate other tile data as well.

We'll probably need some type of config (JSON naturally) for the function that could include things like the triggering event itself (user click, pre/post save...), the endpoint, whether it should run during import, etc...

If that all makes sense, then we'll probably need to add a functions_x_nodegroups table to support this.

**Comment by robgaston** [comment]
Do we have to support item 2?  That isn't clear to me.

A central question is this: Do functions execute outside the context of a user entering data into a form (eg on import of business data)?  If so, we will only be able to implement python based functions in this way (not client-side functions, obviously).

If we must support both client and server functions, then I think that we should explicitly distinguish between client and server functions somehow (probably in both the DB and the UI) so that it is clear when these functions are actually being executed.

RE: the need for a `functions_x_nodegroups` table: functions are currently associated to `cards` and `cards_x_nodes_x_widgets` records in a way that already supports many-to-many relationships.  If we are implementing functions outside of forms, then we should promote these relationships to the `node_groups` and `nodes` tables (for the same reason as we promoted cardinality in this way).

Also, @dwuthrich made a comment in the slack channel which seems to run counter to your, @apeters, assertion that client side functions would "absolutely [not] persist anything to the db," from @dwuthrich:

> Just one little addition: client-side functions could also create new tiles.  Example: a client-side function could automatically create a geometry based on an address geocode (all done via Javascript).  This new geometry could be stored in either the same the function is bound to or a different tile.

This implies that a client function could persist data - we should think through this use case, because it is not clear to me that this actually must be implemented as a client function.  Especially because if it is in fact persisting data, then it seems to me like users may want these kinds of functions to execute on import as well as save of data via a form.

**Comment by apeters** [comment]
> Do we have to support item 2?  That isn't clear to me.

I think we do and I came up with a few good examples I think, but ultimately @dwuthrich will have to weigh in on this use case (although so far, flexibility has been a driving force in the development of v4 and being able to trigger functions based on hooks in the CRUD lifecycle seems like something that could be implemented easily)

> A central question is this: Do functions execute outside the context of a user entering data into a form (eg on import of business data)?  If so, we will only be able to implement python based functions in this way (not client-side functions, obviously).

I can easily imagine scenarios in which some processing needs to take place that doesn't require additional user input, something for example that you want to have happen every time a user saves a certain type of tile.

> If we must support both client and server functions, then I think that we should explicitly distinguish between client and server functions somehow (probably in both the DB and the UI) so that it is clear when these functions are actually being executed.

I agree

> RE: the need for a `functions_x_nodegroups` table: `functions` are currently associated to `cards` and `cards_x_nodes_x_widgets` records in a way that already supports many-to-many relationships.  If we are implementing functions outside of forms, then we should promote these relationships to the `node_groups` and `nodes` tables (for the same reason as we promoted cardinality in this way).

I guess I could see the need for both, the current cards_x_functions table nicely supports UI based functions.  I could see that in different UI contexts (mobile vs desktop) that there may be a need for different functions to be run for cards that reference the same nodegroup (is this a valid use case?).  If we just attached functions to nodegroups then differentiating between UI contexts becomes much more difficult.  

> Also, @dwuthrich made a comment in the slack channel which seems to run counter to your, @apeters, assertion that client side functions would "absolutely [not] persist anything to the db," from @dwuthrich:

> > Just one little addition: client-side functions could also create new tiles.  Example: a client-side function could automatically create a geometry based on an address geocode (all done via Javascript).  This new geometry could be stored in either the same the function is bound to or a different tile.

> This implies that a client function could persist data - we should think through this use case, because it is not clear to me that this actually must be implemented as a client function.  Especially because if it is in fact persisting data, then it seems to me like users may want these kinds of functions to execute on import as well as save of data via a form.

I think of client side functions as running outside the context of a CRUD operation.  So, when @dwuthrich says that a client side function could create a new tile, I suppose it could, but only on the client (persistence to the db wouldn't happen at that time).  When the user finally did click the "save" button, then that new tile (along with the current tile and any other data) would be persisted to the db.  What we want to avoid is a client side function persisting data unbeknownst to the user because if the user decides to abandon their work (exit and not save) then we would have to clean up the data persisted as part of a client function.

**Comment by robgaston** [comment]
Considering the above, perhaps we should have _client-side functions_ (**asynchronous javascript**, which would allow us to query a server [arches or external] in the course of running the function to retrieve more data) associated at the `cards` and `cards_x_nodes_x_widgets` level and _server-side functions_ (**python**, those that would be executed on the server in response to model save events, etc.) would be associated at the `nodes` and/or `node_groups` level.

We can probably leverage the `functions.functiontype` to distinguish between client and server side functions.

In the Graph Manager and Card Designer forms, we should present separate drop-downs for client and server side functions (should get our naming straight there).  Server-side functions could show up in both the Graph Manager and the Card Designer, while client-side functions would (appropriately) only show up in the Card Designer.

Sounds like when it comes to client-side functions, they will be able to act on the data in the current form, but shouldn't actually persist that data back to the server (data will be persisted on form save, as usual).

**Comment by apeters** [comment]
> Considering the above, perhaps we should have _client-side functions_ (**asynchronous javascript**, which would allow us to query a server [arches or external] in the course of running the function to retrieve more data) associated at the `cards` and `cards_x_nodes_x_widgets` level and _server-side functions_ (**python**, those that would be executed on the server in response to model save events, etc.) would be associated at the `nodes` and/or `node_groups` level.

I agree, with the exception that probably the **server side** triggered functions would be attached at the `node_groups` level **only** since that is our most granular unit of data.

>We can probably leverage the `functions.functiontype` column to distinguish between client and server side functions.

agreed

> In the **Graph Manager** and **Card Designer** forms, we should present separate drop-downs for **client-side functions** and **server-side functions**.  **Server-side functions** could show up in _both_ the **Graph Manager** _and_ the **Card Designer**, while **client-side functions** would _only_ show up in the **Card Designer** (as they assume a client).

I agree.  It seems that maybe, like cardinality, we present the **server-side functions** dropdown in **only** the **Card Designer** forms, but then attach them to the cards associated `node_group` table.  I think this will simplify the UI a bit.  Also, **client-side functions** should encapsulate any reference to **server-side functions** from within the function itself.  That is, a user shouldn't be expected to some how **chain** a **client-side function's** asynchronous request to a **server-side function**.  That should be defined directly within the **client-side function** itself.

I expect that we'll define two **abstract** base classes for the **server-side functions**, one that assumes a request another that doesn't and we can then use that fact to differentiate the **server-side functions** that need show up in the **Card designer** and ones that shouldn't.

> Sounds like when it comes to client-side functions, they will be able to act on the data in the current form, but shouldn't actually persist that data back to the server (data will be persisted on form save, as usual).

exactly

**Comment by apeters** [comment]
I've been thinking about Functions/Validations and how to implement them, and the more I think about it, the more it seems that if we're clever (and we are!) we can leverage functions to handle several use cases.

- Datatype validation (node values conform to their respective datatypes)
- Search filtering (saved searches)
- Search filtering (permissions/logic based filters)
- General functions (implementation specific)

It seems that in fact we might be able to say that **validations are really just functions** of type validation (which would go a long way to clearing up the ambiguity between the 2, note that they currenlty share the same schema signature)

The way I see it we can have several types of functions each backed by a corresponding abstract class in code. For example, the datatype validation function would expect to receive a value and return a boolean.

In the ui we could still make a distinction between validation functions and other functions based on type or some other flag.

If this is something we can get behind I'd like to create a ticket for this and then use as a first test case Datatype validation as this can be tested during import.

**Comment by dwuthrich** [comment]
I agree that in practice there is very little difference between validations and functions, so making the implementation as simple as possible makes sense. In terms of use cases, validations focus on confirming data values (making sure that values match node datatypes is the obvious case).  

But validations also will check for formats (e.g.: the "Telephone" node has datatype string, and should implement a particular format for the string value).  It looks like this JS library could prove helpful in these situations: https://validatejs.org/#validate-js

**Comment by robgaston** [comment]
@apeters if I follow you correctly, when you talk about "leveraging functions", you are talking about whatever the backend implementation for these things is?

If so, then I think I agree that we can use a single interface for executing validations (both user defined and  based on datatype) and functions, and probably also use that elsewhere (as in your example of search). The basic idea is: these things process values inside of tiles and either do something or tell you something.

I don't think we should necessarily change our database schema around validations and functions, though.  There are a number of foreign key relationships defined to both of these tables and we have management of these entities currently working with the schema as implemented.  We could remove the validations table and put those records in the functions table, but I'm skeptical of the value of that change and it could be a lot of effort to get things back in working order.

I would argue for three separate db entities (as we have now): `functions`, `validations`, and `d_data_types`; each of which would implement the same methodology (python based) for executing logic against values inside `tiles.tiledata`.  `functions` where the `functiontype` indicates that they should run on the client will use a similar methodology, but it will have to be javascript based and will run on the client.

**Comment by robgaston** [comment]
The server side implementation here seems related to our `Tile` (and perhaps to a lesser extent `ResourceInstance`) model.  Perhaps validations defined by a user in the `validations_ x_nodes` table and implied by the selected `node.datatype` as well as server-side functions can all be managed by our `Tile` model.  I'm thinking that these will be executed when we save `Tile` models.

Functions that are meant to execute on the client should probably always react to viewmodel changes, as opposed to save events. Since saving always requires a request, these kinds of functions can always be server-side.  Client-side functions are primarily for reacting to a user's interaction with a form before they actually save it, so I think that client-side functions can just be subscribers to the tile value's viewmodel.

**Comment by robgaston** [comment]
As far as the kind of format checking that @dwuthrich has described, this can happen at multiple levels as we've currently modeled things, one could:

1. create a datatype called 'telephone number' whose datatype validation would do that format checking
2. create a `validations` record that is associated with the datatype 'string' that points to a function that checks the format of the string
3. create a `widgets` record that is associated with the 'string' (or 'telephone number', as the case may be) that points to a widget that enforces the entry of a phone number.

Chances are, you'd probably actually want to do both 2 and 3, but 1 could also work (especially if you had a lot of nodes representing phone numbers).

**Comment by apeters** [comment]
> I would argue for three separate db entities (as we have now): functions, validations, and d_data_types; each of which would implement the same methodology (python based) for executing logic against values inside tiles.tiledata. functions where the functiontype indicates that they should run on the client will use a similar methodology, but it will have to be javascript based and will run on the client.

I would propose that we remove the current `functions` table and rename all `validation*` tables to `function*`.  Right now in the `functions` table we are essentially mixing `nodegroup` based functions (they use functiontype `card`) with `datatype` based functions (they use functiontype `string`, `concept`, etc...).  The later would nicely be handled by `valdiations_x_datatypes` (soon to be `functions_x_datatypes`) table. The former are either client side functions that react to direct user interaction, view model changes, etc.., or they are server side functions that react to tile CRUD operations.

> The server side implementation here seems related to our Tile (and perhaps to a lesser extent ResourceInstance) model. Perhaps validations defined by a user for a particular node in the validations_ x_nodes table, validations implied by the selected nodes.datatype, and server-side functions can all be managed by our Tile model. I'm thinking that these will be executed when we save Tile models.

When a Tile is saved it will introspect the nodegroup id and node id to see if any functions are attached at either of those locations.  Server side functions attached to the `validations_x_datatypes` (proposed to be `functions_x_datatypes`) via the node.datatype will be executed along with functions that are generically associated with nodegroups via the `validationtype(functiontype)` field.

> As far as the kind of format checking that @dwuthrich has described, this can happen at multiple levels as we've currently modeled things, one could:

> 1. create a`d_data_types` record called 'telephone number' whose datatype validation would do that format checking
2. create a `validations` record that is associated with the datatype 'string' that points to a function that checks the format of the string
3. create a `widgets` record that is associated with the 'string' (or 'telephone number', as the case may be) that points to a widget that enforces the entry of a phone number.

> Chances are, you'd probably actually want to do both 2 and 3, but 1 could also work (especially if you had a lot of nodes representing phone numbers).  3 would not be required, but if you did not do this, the user would not know that their entry was invalid until after trying to save.  If you did 3 and not 1 or 2, the UI would enforce entry of a phone number, but the format wouldn't be checked on import of business data.

I agree the 2 and 3 are what you'd want to do at a minimum.  Item 2 for the import and save, 3 for good UI and user feedback

**Comment by robgaston** [comment]
`validations_x_datatypes` is used to define which `validations` are appropriate for a node given it's  datatype (not for attaching validations to datatypes in the way that you've described).  `validations` are actually assigned in `validations_x_nodes`.

My assumption was that we could have a function/validation implicitly assigned to each node based on it's datatype, and therefore, we wouldn't need any additional entities for assigning validations to datatypes as you described.

The `functions` table would only represent those functions which can be assigned by a 'Card Designer' (as opposed to a graph editor) and are as such associated at the card level.

**Comment by apeters** [comment]
> `validations_x_datatypes` is used to define which `validations` are appropriate for a node given it's  datatype (not for attaching validations to datatypes in the way that you've described).  `validations` are actually assigned in `validations_x_nodes`.

that keeps catching me out, but in any case we'll get the appropriate validation/function to run from the `validations_x_nodes(functions_x_nodes)` table 

> My assumption was that we could have a function/validation implicitly assigned to each node based on it's datatype, and therefore, we wouldn't need any additional entities for assigning validations to datatypes as you described.

we could, by leveraging the `validationtype(functiontype)` field 

>The `functions` table would only represent those functions which can be assigned by a 'Card Designer' (as opposed to a graph editor) and are as such associated at the card level.

I actually think that we would want all functions to reside here.  Functions that can be assigned by a _Card Designer_ as well as implicit functions like datatype validation functions or processing functions meant to be used by a client-side function.  We would probably want to add and extra field or two to the functions table to be more explicit about where/how functions get used as opposed to using magic key words in the `validationtype(functiontype)` field

**Comment by apeters** [comment]
this is currently implemented by functions
