### ISSUE TITLE
Create a singleton to cache reusable, complex objects that are expensive to instantiate and serialize

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#6832]
If graphs are not being edited in the graph designer, we should be able to assign them, and their components (cards, nodes, etc) to a singleton for reuse across the application. A serialized version of each object could be saved to the singleton as well.

**Comment by apeters** [comment]
Using graph singletons isn't a viable way to improve performance for several reasons.
1.  Everywhere you use the ORM would have to be modified to use the singleton.  EG: models.Graph.objects.get() would need to be modified.  Also, using objects.filter wouldn't be able to be transformed to use the singleton as easily.
2. Because graphs are composed of many constituent components, the singleton would have to account for any changes to those components.

Node cacheing might be the way to go instead.  
Closing for now.
