### ISSUE TITLE
Tiles for certain cards are in a dirty state after import

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#6982]
In my environment, I am seeing that on these cards in ssc app:

unit.inspection
fiscal year.fiscal year
fiscal year.billing parameters
Sewer Service Charge.Summary
Sewer Service Charge.Unloaded Flow
Sewer Service Charge.Permit Fees

![image.png](https://images.zenhubusercontent.com/56f150f76caf56c9d38e16f8/6d73f509-c971-4fa8-916e-a1ce071e98ef)

**Comment by chiatt** [comment]
@adamlodge Does this occur in the very latest in stable/5.1.x? This seemed to occur with the number datatype, but @njkim committed a fix that should be in the latest.

**Comment by adamlodge** [comment]
@chiatt Still seems to be occurring.  I pulled latest stable 5.1, reloaded the package and data, and tiles still coming across in a dirty state after load.

**Comment by chiatt** [comment]
@adamlodge Is it possible that these cards have default values that are not getting populated in the package load? That might cause the tile to be dirty in the UI because new, default data is getting automatically added to the tile. That's not to say it's not a problem, but it would explain the behavior.

**Comment by chiatt** [comment]
Resolved in #7005
