### ISSUE TITLE
Widget: Default config of Date Widget

### ISSUE THREAD

**Issue by jmunowitch** [archesproject/arches#720]
What should be the config for the default Calendar Widget and Date datatype be

**Comment by jmunowitch** [comment]
### Default Widget Config:
```
{
    'defaultdate: '2007-03-01',
    'datemin': '2000-01-01',
    'datemax': '2010-01-01'
}
```


### Default Datatype Config:
```
{
   'date': '2007-03-01'
}
```

**Comment by apeters** [comment]
Does this just handle dates or dates and times? 
For example javascript's Date object includes both.

`new Date().toISOString() = "2016-09-02T16:55:39.565Z"`

**Comment by jmunowitch** [comment]
I think this is a good question on how we want to store and display this type of data in regards to specificity. 

Do we want to store the data as a string in the ISO standard as @apeters points out? 

How do we want to specify uncertainty or date ranges?

**Comment by robgaston** [comment]
I think dates should look something like this:

### Default Widget Config:
values would be `null` by default, but could be overridden w/ ISO standard date strings
```
{
    "defaultdate": null,
    "datemin": null,
    "datemax": null
}
```


### Default Datatype Model:
an iso standard date string
```
'2016-09-02T16:55:39.565Z'
```

**Comment by apeters** [comment]
The datatype model should allow users to specify whether or not to include time data.

```
{
     'default_date': null, 
     'include_time': false
}
```

**Comment by robgaston** [comment]
@apeters I think you are referring to either the `d_data_types.defaultconfig` or `widgets.defaultconfig`; the "Default Datatype Model" refers to the object that we'll actually store in `tiles.tiledata`, which I think should just be a string representation of a date.

An alternative way to handle this could be to just ship two widgets - a date picker and a date time picker.  Assigning one of those widgets would imply whether time should be considered. 

For consistency we could always just store ISO string dates (which would include time) and we can use our widgets to determine whether or not the time is displayed to the end user in forms & reports.

**Comment by apeters** [comment]
I just want to make sure that "time" data isn't saved by the user unknowingly.
That is, if a user can't define the time then time isn't saved as part of the value and is just hidden from the user (because it's still in the data, and that's a problem).

This makes me wonder if we should have a **fuzzy date** datatype.  Something that doesn't have to conform to the ISO date standard but that is intended to represent **date-like** information.  
Eg: "2398 BC"

Something that would inform the system that it should try and parse the string to glean date like information from it mainly for searching.  I'm mostly thinking about data import right now.

**Comment by robgaston** [comment]
@apeters I was thinking along the same lines - we could have a separate datatype for tracking dates as an integer years since 0 (eg 2398 BC could be represented as -2398) to handle the kinds of values that you've described.

**Comment by jmunowitch** [comment]
Has this met requirements?

**Comment by dwuthrich** [comment]
meets requirements
