### ISSUE TITLE
Consultations Workflow: Creating new Application Area from Related Resources widget can result in 2 instances

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#7495]
When creating a new app area from the related application area widget in the first step of the workflow, the order of input operations matters.

If the user enters the geometry of the application area first, then adds a value for the app area name Arches creates 2 application area instances, one with a geometry (but no name) and a second with a name (but no geometry).

If the user enters the name of the application area first followed by the geometry, then Arches creates a single instance with both name and geometry, as expected.

Not sure what happens if the user creates a different tile (e.g.: not the geometry card) before entering a name

**Comment by chiatt** [comment]
It turns out this occurs with other resource models as well. If the user edits a card other than the top card, an instance is created. If they then edit the top card, a second instance is created. Subsequent card edits will continue to modify the instance created in the top card while the first instance that was created will only have a tile from the first edit.

**Comment by chiatt** [comment]
Resolved in #7498
