### ISSUE TITLE
Allow inclusion of report link in CSV or SHP export

### ISSUE THREAD

**Issue by csmith-he** [archesproject/arches#7541]
**User Story**
In the Export Search Results, the user can toggle the option to include the full report URL in the CSV or SHP export

**Acceptance Criteria**
-   [ ] When Report Link is toggled to true, the full report link is exported in standard CSV or SHP export
-   [ ] When Report Link is toggled to true, the full report link is handled correctly by Celery process and CSV or SHP export is successful
-   [ ] Tests passed (requires in person testing for UI)
-   [ ] Documentation

**Definition of Done**
The full report URL, correct to the instance of Arches being run, is displayed in the CSV or SHP export for each resource regardless of whether or not the process is handled in standard fashion or passed off to the Celery process.  Report link is not included if the toggle is set to false.

**Note**
We're currently working on this for Keystone
Accessibility element (e.g. aria labels) for UI to be added as part of the main Accessibility work

**Ticket Background**
*   Sponsored by: Historic England
*   Suggested by: @csmith-he 
*   Designed by: @csmith-he

**Comment by chiatt** [comment]
@csmith-he - It seems like this could just be a Django setting rather than a toggle in the UI. Using a setting would keep the UI and Python code simpler and make inclusion of the link easier to implement across formats other than CSV and SHP. Regarding Keystone, is it necessary for users to control whether the link is in the export output or not? If not, I think it would be better just to let the admin make the decision with a setting at the project level.

**Comment by aj-he** [comment]
@chiatt @csmith-he This was asked to be included by Keystone project but was also a requirement for Warden but was push out of MVP due to time pressures. People generally want the option to be able to look back at the full record easily should they wish to when only a subset of data is included in the export.

With regards to the UI option, there are instances where for internal purposes people want to have the URL but when doing an export for an external customer don't want that included.

We would prefer the UI option to remain. Perhaps we submit the PR for you to review the extent of the feature?

**Comment by chiatt** [comment]
Thanks @aj-he, that makes sense. I'd be happy to take a look at a PR once it's ready.

**Comment by chiatt** [comment]
Resolved in #7586
