### ISSUE TITLE
Related Resources tabs bar in search page doesn't work

### ISSUE THREAD

**Issue by YuvalShafriri** [archesproject/arches#7637]
Hi , [see my post on the Arches Project forum](https://community.archesproject.org/t/isuue-with-related-resources-graph-on-search-results-page-latest-5-2-x/1355?u=yuval_shafriri)
Seems to be related to #7360
 If it's not a bug please let me know how to make it work...
 Thanks:)

**Comment by robgaston** [comment]
@apeters can you please add steps detailing how you reproduced this bug?

**Comment by YuvalShafriri** [comment]
I checked it today after fetching last commits. Now the tabs bar works - after clicking on "related" filter, but only when you click on "map" link in serach results before clicking related filter.  So If there is no mapas part of the the resource, it still doesn't work.
Also it will not work by selecting the result item only, or by clicking "details" , only by clicking on "map".

**Comment by chiatt** [comment]
Hi @YuvalShafriri - were you able to get this resolved? The 'edit' and 'related resource' links should have still been appearing for you. Is it possible that you were using the Arches HER project? If that were the case, there may have been a bug preventing those links from appearing. In any case, in the latest version of Arches HER, the issue is resolved.

**Comment by YuvalShafriri** [comment]
Hi @chiatt , it works fine for me on various installations **since September**, also on HER project,
so i don't think there is a bug here now

**Comment by chiatt** [comment]
Thanks @YuvalShafriri - Glad to hear it.
