### ISSUE TITLE
Related Resources link buttons on the search results does not show

### ISSUE THREAD

**Issue by aj-he** [archesproject/arches#7840]
**Describe the bug**

In search results the related resources link on the search results dopes not appear even though . It looks as though the `userCanReadResources` and `userCanEditResources` is not making it from the `view-data` into the search-results viewmodel.

Adding lines 33 and 34 int he image below makes it work as expected.

**Screenshots**

![image](https://user-images.githubusercontent.com/25295526/134538153-ce2ae4a6-90ed-4d23-b863-4f193ed29006.png)

**Your Arches Information**

*   Version used: 5.2.x
*   Operating System and version (desktop or mobile): Windows
*   Browser Name and version: Chrome Version 93.0.4577.82 (Official Build) (64-bit)
*   Link to your Arches Install (optional):

**Additional context**

**Ticket Background**
*   Found by: @aj-he

**Comment by robgaston** [comment]
@chiatt were you able to recreate this? In my testing I've not seen this, so I suspect that (while the proposed code change looks reasonable) this might be a project specific bug...

**Comment by chiatt** [comment]
@robgaston I can only reproduce in HER. I suspect this is because quite a bit of search in HER is customized and files that are overriding core functionality in Arches need to be updated.  That customization may be going away though because there is a proposal to remove the 'Find' page. https://github.com/archesproject/arches-her/issues/697

It looks like search.js is getting overridden in HER and needs to be updated to reflect these changes: https://github.com/archesproject/arches/pull/7676/files

**Comment by chiatt** [comment]
Replacing this issue with: https://github.com/archesproject/arches-her/issues/712
