### ISSUE TITLE
Graph Manager: Clicking on CONCEPT nodes in left panel creates imperceptible Edits that can't be discarded or saved

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#816]
go to either "Arches configuration" or "Heritage Resource" (current default resources in the dev installation) and click on a concept node in the left node list panel.  the node is selected, but some change has been made that triggers the Discard Edits button to show up.  neither the Discard Edits or Save buttons work.

**Comment by mradamcox** [comment]
This also happens if you click the node itself in the graph, not where it is shown in the node list panel.

**Comment by apeters** [comment]
I think this happens because these graphs are really old and are not consistent with our current rules for creating a graph.  If you test on a graph that you create yourself, you'll see this doesn't happen.
Those 2 graphs ( "Arches configuration" and "Heritage Resource") will be reimagined soon I believe.

I'm closing this for now based on the above assumptions.
