### ISSUE TITLE
[webpack] Investigate how components declared in templates can be used

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#8198]
### To Reproduce

1. set up webpack ( see: https://github.com/archesproject/arches/pull/8190 )
2. insert a `console.log(arches)` statement into `js/models/mobile-survey.js` before the return statement
3. navigate to `localhost:8000/user`
4. notice that the user page hangs with the error `Cannot read properties of undefined (reading 'collector_designer')`

### Contextual Knowledge

- this is not happening only with `arches`, but all components that are declared in templates ( eg `view-data`, `graph-designer-data`, `plugin-data`, etc etc )
- notice `arches` has been logged as a 'Module' dict where the `default` key is paired with the HTML of `templates/javascript.htm`, this is because `'arches': Path.resolve(__dirname, '../../templates', 'javascript.htm'),` has been declared as an alias in `frontend/webpack/webpack.common.js`
- a path we'd like to avoid when solving this issue is to replace the declaration with a call to an API endpoint. We should leverage the ability to pass data directly from django -> template -> JS component
- an interesting possible alternative is hanging these definitions on the window. For instance, in `javascript.htm` if we remove the `define` statement and instead hang the return object on the window, it can be seen by the module
  - HOWEVER it does not seem to have django value interpolation

**Comment by aarongundel** [comment]
More notes on this: we deduced that a lot of this is just due to the fact that if we pack templates without running them through the server, the django tags aren't resolved.  This causes an interesting set of problems that are difficult to resolve without hanging the items somewhere globally (in our case on window) that is run through the server.  This is particuarly problematic when components go to pull in their templates via require - in short, they can't pull them through webpack because the django tags aren't resolved.  So a stopgap we've taken to using is putting those templates on the window.

**Comment by chrabyrd** [comment]
resolved in latest
