### ISSUE TITLE
EDTF Date fields accepting any format

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/arches#8282]
**Describe the issue** - EDTF date fields are accepting dates that are not in EDTF format, should there be validation added.

**Steps to reproduce**

1) Open a Heritage Asset record

2) Click on the Scientific Date Assignment card

3) Enter the start/end dates in the format shown below and save the card:

![image](https://user-images.githubusercontent.com/78143228/152209451-f3659d7b-b287-46f5-a297-990d943e5741.png)

**Comment by chiatt** [comment]
@rlwilliamss The edtf input accepts non-edtf dates and then converts them to correct edtf before the data is indexed in ElasticSearch. This is intended to be convenient for the user, but it can be confusing if you're unaware this conversion is happening. To address this, @njkim has changed the input so that you now see a preview of what is going to be saved and indexed.
