### ISSUE TITLE
7.0.x graph publication import/export has destabilized

### ISSUE THREAD

**Issue by chrabyrd** [archesproject/arches#8323]

**Comment by chiatt** [comment]
This problem surfaced because we are no longer publishing and serializing graphs during the 6.1 to 7.0 migrations. We cannot serialize graphs in a migration because the graph proxy model does not work as expected in migrations. 

Proposed solutions:
1. Do nothing and let users migrate from 6.1 to 7.0 and manually publish their graphs. This would require that we provide instructions to do so in the v7 release notes.
2. Create the published graph records in a migration, but don't serialize. Then write an 'upgrade project' command that will publish graphs for the user. This may also be useful if there are other steps that we can automate to ease upgrading for users.

**Comment by chiatt** [comment]
Resolved in #8618
