### ISSUE TITLE
Elastic Search exact term matching makes it difficult to find results

### ISSUE THREAD

**Issue by rlwilliamss** [archesproject/arches#8355]
**Issue Description** - Exact term matching - If an exact search term is given for a concept value, a list of all matches is given, and you must find the exact match somewhere in the list. It would be good for exact matches to be put at the top or selected by default, e.g., ‘Pit’ has an exact match, but all instances of pit are listed – possibly in collection order.

(priority 2 – enhancement) Example in screenshot - Heritage Asset ---> Functional Type.

![image](https://user-images.githubusercontent.com/78143228/127346123-9d67141f-8238-4033-987f-4bdd833cabe5.png)

**Comment by chiatt** [comment]
We actually don't use ElasticSearch to drive the concept dropdown. Postgres is better suited to the task because the data is hierarchical, so instead a recursive sql query is used. Because we aren't using Elastic, we don't have a search score which can be used to order matches. We can, however, check for exact matches and list those above the concept tree. This is something that probably should be done in core arches rather than a custom widget because it would require modifying backend code.

**Comment by chiatt** [comment]
Resolved in #8378
