### ISSUE TITLE
IIIF Annotation tile data not viewable in report

### ISSUE THREAD

**Issue by whatisgalen** [archesproject/arches#8419]
**Describe the bug**

When creating IIIF Annotation data in arches stable/5.2.x, the data is not really viewable because the iiif viewer box is too narrow (see screenshot). You can see that the data is there, though

**To Reproduce**
1. Create IIIF Annotation data in a vanilla arches project using stable/5.2.x
2. view the data in the resource report

**Screenshots**

![Screen Shot 2022-05-12 at 8 46 03 AM](https://user-images.githubusercontent.com/8366985/168115922-4d1e7b74-fd9a-4575-a52b-9bc3c9088582.png)

**Expected behavior**
The viewing box should be roughly as wide as the GUI used to create the Annotation data

**Your Arches Information**

*   Version used: stable/5.2.x
*   Operating System and version (desktop or mobile): ubuntu 20
*   Browser Name and version: chrome 101.0.4951.64
*   Link to your Arches Install (optional):

**Additional context**

**Ticket Background**
*   Found by: @

**Comment by zoometh** [comment]
The [EAMENA database](https://database.eamena.org/en/) is currently Arches v5.2 and we plan to upgrade it directly to Arches v7.

We found the bug mentioned by @whatisgalen with the IIIF viewer (same computer settings). In addition to the view box being too narrow, no popup window appears when annotations are clicked on (therefore no additional data is visible).

**Expected behaviour**
The annotations (points, lines, polygons) should display the data recorded in the different IIIF sub-nodes (e.g. date of the photograph, author).

**Comment by chiatt** [comment]
This appears to still be an issue in v7.

**Comment by Habennin** [comment]
It also appears to be an issue in 6.1 still

**Comment by takinsolutions** [comment]
It is an issue in 6.1. 

Would it be fixed anytime soon? 

It is a major blocker for a large project I'm working on depending on image viewing and annotations.
