### ISSUE TITLE
Test that all datatypes load as expected via the staging table

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches#8420]
Ensure the following datatypes load as expected via the staging table:

- [x] string
- [x] number
- [x] file-list
- [x] concept
- [x] concept-list
- [x] geojson-feature-collection
- [x] domain-value
- [x] domain-value-list
- [x] date (with and without time)
- [ ] node-value
- [x] boolean
- [x] edtf
- [x] annotation
- [x] url
- [x] resource-instance
- [x] resource-instance-list

**Comment by chiatt** [comment]
Annotations take a JSON object with no quotes around it: ```{"type":"FeatureCollection","features":[{"id":"e0704264-7ab9-4e8c-9742-455e669f1717","type":"Feature","geometry":{"type":"Point","coordinates":[53.350067,-75.775361]},"properties":{"color":"#3388ff","canvas":"https://media.getty.edu/iiif/image/793da8e8-cf67-472c-8746-234e637d77af","nodeId":"97c30c42-8594-11ea-97eb-acde48001122","radius":10,"weight":3,"opacity":1,"manifest":"https://media.getty.edu/iiif/manifest/a91a88a3-ca07-480f-b749-8e1c28d4f040","fillColor":"#ff0000","fillOpacity":0.2}}]}```

**Comment by chiatt** [comment]
geojson-feature-collection takes WKT just as it does in the standard csv importer. example:
```
POLYGON ((30 10, 40 40, 20 40, 10 20, 30 10))
```

**Comment by njkim** [comment]
### number
- [ ]  transform_value_for_tile needs to catch ValueError: datatypes.py L.186, eg. "six"

### boolean
- accept true: y, yes, t, true, on and 1; false: n, no, f, false, off and 0 (distutils.util.strtobool)

### date / datetime
- need to be string from excel, eg. '2022-03-04 (Excel auto-formatted datetime will create an issue)

### concept / concept-list
- accept uuid or value both working
- concept-list accepting comma separated values w/o spaces, error for concept
- does NOT check whether or not the value is in the right concept collection, but the value will show

### domain / domain-list
- accept uuid but not value
- domain-list accepting comma separated values w/o spaces, error for domain 
- does NOT check if domain id is available, but none will show
- [ ] core bug? domains changes other nodes domains changes (inconsistently)

### resource / resource-list
- accept only list of the object form (both resource and resource-list)
eg. (can skip resourceXresourceId)
`[{"resourceId": "00f3c4cf-2034-420c-855d-05e8cb45436e", "ontologyProperty": "", "inverseOntologyProperty": "", "resourceXresourceId": ""}]`
- does NOT check if the x-resourceid is avalable
- [ ] currently resourceid_x_resourceId won't be created (#8431)

### edtf
- [ ] cause a problem because the transform_value_for_tile return a tuple

### url
- accept both object form and address, eg. {"url": "https://google.com", "url_label": "Google" } or https://google.com
