### ISSUE TITLE
Resource Editor: Wire up "Review Edit History" tool in "Manage..." menu

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#897]
### Bug Report

The "review edit history" button should show the edit history of the resource as mocker up in arches_resource_editor_v2.html

**Comment by adamlodge** [comment]
@chiatt: I was able to successfully add, edit, and delete a site name and see the history of those edits after the edits have occurred.  Is there more that I should be testing for?

**Comment by chiatt** [comment]
@adamlodge You should probably make sure that you can sort edits by type, editor, and time (oldest and most recent).  Also check that the resource model name and icon appear correctly in the header as well as the resource instance display name.

**Comment by adamlodge** [comment]
@dwuthrich 
I think this implementation sufficiently mimics the mockup to warrant closing the ticket.
 However, unlike the mockup, it looks a like a design decision was made to launch the edit log view in a separate tab with its own url.  I like this deviation, btw, because it allows a user to refresh the edit log page and watch it grow as edits are applied.

I am a bit unclear on the specific use cases that are intended to be met with the edit log apart from mimcing the mockup, so I am a bit hesitant to say "meets requirements".  Questions also occur to me around additional (likely future) functionality such as rollback of edits and analysis of edit data.
