### ISSUE TITLE
Calendar glitch with missing month/year options

### ISSUE THREAD

**Issue by kkemp85** [archesproject/arches#9060]
Arches Version/Branch: dev/6.2x

Describe the bug and how to reproduce it: 
Before our upgrade to Arches 6, we had issues with the Date Interval calendar. The month/year options are blank when you click on them to switch to a different month/year. @mradamcox and I discussed the issue and he noted seeing it on other Arches instances he manages.

![Missing months](https://user-images.githubusercontent.com/54329725/198685124-c99a8595-f53f-4640-9ddc-31b1f78ff997.png)

![Missing year](https://user-images.githubusercontent.com/54329725/198685121-8f94f078-a370-4530-be61-292194eab013.png)

**Comment by mradamcox** [comment]
We are seeing this in dev/6.2.x, but I have not been able to try any Arches 7 installations. There are no errors in the dev tools console, so perhaps its a problem with the underlying js library.

**Comment by mradamcox** [comment]
Did a little more digging on this, and apparently it is still an issue in v7.2 at least. I assume it's because the `eonasdan-bootstrap-datetimepicker`  that Arches uses, `4.17.44` is out of date. Likely related to an issue like this, https://github.com/Eonasdan/tempus-dominus/issues/2295, which indicates that version 4 is no longer supported, and upgrading to the later 6 release (or perhaps using a different datepicker) seems like a good next step toward fixing this issue.

**Comment by chiatt** [comment]
I believe the date widget and the search filter use the same datepicker, and it seems to be working fine in the widget. 
This is from 6.2.2:
![image](https://user-images.githubusercontent.com/1877663/219823922-604686a6-e35f-4dc4-9e54-acc745e350b9.png)

**Comment by mradamcox** [comment]
Oh good catch. Perhaps there is rogue CSS on the search page.
