### ISSUE TITLE
Problems with yarn build_production

### ISSUE THREAD

**Issue by nicospor** [archesproject/arches#9107]
Hi,

we're running Arches 7.2 in a production environment with Ubuntu 22.04, gunicorn and Nginx, serving a custom project.

When we try building static files using `yarn build_production`, the command gets stuck after seemingly having generated the templates and it uses up all available memory until it crashes with a `137` error, even when allocating more memory to the script (it looks like a memory leak).
This doesn't happen when running `yarn build_development`.

Also, it seems that updating views in `templates/views` doesn't have any effect because they are not copied to the `staticfiles` folder, so Nginx continues serving the older versions. The same issue occurs in relation to the project's custom CSS file in `media/css`, although the respective `<link rel="stylesheet">` element has been correctly added to the `main-base.htm` template, as per Arches documentation.

This apparently doesn't happen when updating templates in the main root dir, i.e. `templates/`, since changes to e.g. `index.htm` are correctly reflected in the browser.

**Comment by chrabyrd** [comment]
Hi @nicospor 

Thanks for reaching out with a detailed error report. 

- `yarn build_production` is a very heavy call, on an 8GB AWS instance it takes between 1 and 2 hours to run. This is mostly due to the minification flag passed into the production webpack build. You should be able to update your project's local `webpack.config.prod.js` to not minify the bundle, which should considerably cut down on the resource allocation / build time.

- There are a few differences between `yarn build_development`, and `yarn build_production`. `yarn build_development` simply creates a frontend bundle in the `media/build` directory, while `yarn build_production` creates the frontend bundle and **also** calls `collectstatic`. If you're attempting to see changes after running `yarn build_development`, you'll need to also manually run `python manage.py collectstatic`. You'll need to complete this process every time a frontend change has been made.

I'm closing this ticket for now as all behavior outlined in it is known and expected. If you think that's an error please feel free to reopen the ticket and add more context 👍
