### ISSUE TITLE
Can GeoJSON include other attribute data as well as spatial data?

### ISSUE THREAD

**Issue by rebeccawilliamss** [archesproject/arches#9328]
Test shapefile created from HBSMR APA layer in HBSMR covering the City of London to use as a buffer file in Arches.

1) Converted test shapefile to GeoJSON using online converter (https://mapshaper.org/)

- Question: Do we need another stage in the process to convert the shapefile from OSGB36 to WGS84 or does Arches take care of that?

2) Opened the new converted GeoJSON file in Notepad ++ and copied data text

3) In Arches, already opened in Chrome Pane: Find>Filter>Select a filter (Draw a polygon)>Edit GeoJSON>paste test GeoJSON data text>Accept GeoJSON, but nothing happens.

- Question: GeoJSON code added included other attribute data as well as spatial data, description text, Record type, etc.  Do you have to strip out all the attribute data other than the spatial data for the buffer to work in Arches?  Don’t have to do this in ArcGIS Pro when buffering.

**Comment by chiatt** [comment]
You can include additional values in each features 'properties' object. Arches does not transform the projection for you. 
I just checked in v7 and pasting geojson into the Edit GeoJSON panel updates the geometries as expected. It could be that this was a bug that has since been resolved in the latest.
