### ISSUE TITLE
Resource Editor: Arches allows user to select an incompletely defined resource

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches#948]
### Bug Report

Arches allows users to select incompletely configured resources. Steps to reproduce:
1. Create new resource model, but add no cards, forms, reports.
2. Go to resource editor and click on jsut created resource
3. Observe that Arches hangs

see: http://recordit.co/K3NgLqm3oW

**Comment by ryan86** [comment]
This happens when a resource model has no data entry forms. In which case you cannot 'create a resource' from this resource model. I have disabled the 'create resource' button for resource models that do not have forms. 

Do we want to create a contextual warning to let users know why the 'create resource' button has been disabled? What should this look like?

**Comment by dwuthrich** [comment]
This doesn't appear to be resolved.  The vertical menu still allows a user to access edit mode of incompletely defined resources

**Comment by ryan86** [comment]
@dwuthrich ready to be re-QA'd along with #943

**Comment by dwuthrich** [comment]
Not resolved.  Arches allows users to try an edit a resource with all forms set to "hidden" from both the vertical menu and the resource manager page

**Comment by dwuthrich** [comment]
User can still try and edit a resource without forms from the vertical menu list

**Comment by ryan86** [comment]
Added arches-menu-item-disable css class to arches-nifty.css and wired it up to menu item anchor tag when anchor tag is inactive.

**Comment by dwuthrich** [comment]
meets requirements
