### ISSUE TITLE
Create Branch Publication Event (E12)

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#989]
### User Story

As a developer of resource models, I want a CRM-compliant branch for recording Publication_Event.E12 so it is available to me to append to a resource model that I may develop.

Applies to resource models: Information Resource
#### Definition of Done
- [x] able to be attached to the parent resource node
- [x] includes appropriate metadata (ie name, author "GCI", abstract, status = active)
- [x] check that edges have appropriate properties
- [x] proper node data types
- [x] branch stored on QA instance
- [x] branch stored on repo

**Comment by ryan86** [comment]
Notes
- Cannot be related to Information Resource with P108 property.

**Comment by annabelleee** [comment]
Modified the branch to eliminate instance of E39 Publisher as E39 Actors should be independent resources and related to the Information Resource with relationship type as Published/Publisher of. Also added a top node of Publication (E84), in order to connect to the Information Resource resource model.
