### ISSUE TITLE
Create Branch Temporal Coverage (E4)

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches#994]
### User Story

As a developer of resource models, I want a CRM-compliant branch for recording Temporal_Coverage.E4 so it is available to me to append to a resource model that I may develop.

Applies to resource models: Information Resource
#### Definition of Done
- [x] able to be attached to the parent resource node
- [x] includes appropriate metadata (ie name, author "GCI", abstract, status = active)
- [x] check that edges have appropriate properties
- [x] proper node data types
- [x] branch stored on QA instance
- [x] branch stored in repository

**Comment by annabelleee** [comment]
Temporal coverage timespan.E52 was originally conceived as a string field, so that different ways of expressing a timespan could be entered (ex. 1980, 1980-1983, the Bronze Age, etc.). This might prove problematic if we want to treat this as a date for filtering the temporal coverage. Currently, it's set to be a concept field.

**Comment by annabelleee** [comment]
Changed Temporal Coverage Timespan E52 to string.
